// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: switching.proto

package com.switching.v1;

public interface BatchPaymentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:switching.v1.BatchPaymentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .switching.v1.PaymentResult results = 1[json_name = "results"];</code>
   */
  java.util.List<com.switching.v1.PaymentResult> 
      getResultsList();
  /**
   * <code>repeated .switching.v1.PaymentResult results = 1[json_name = "results"];</code>
   */
  com.switching.v1.PaymentResult getResults(int index);
  /**
   * <code>repeated .switching.v1.PaymentResult results = 1[json_name = "results"];</code>
   */
  int getResultsCount();
  /**
   * <code>repeated .switching.v1.PaymentResult results = 1[json_name = "results"];</code>
   */
  java.util.List<? extends com.switching.v1.PaymentResultOrBuilder> 
      getResultsOrBuilderList();
  /**
   * <code>repeated .switching.v1.PaymentResult results = 1[json_name = "results"];</code>
   */
  com.switching.v1.PaymentResultOrBuilder getResultsOrBuilder(
      int index);
}
