// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: switching.proto

package com.switching.v1;

public interface CancelPaymentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:switching.v1.CancelPaymentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uetr = 1[json_name = "uetr"];</code>
   * @return The uetr.
   */
  java.lang.String getUetr();
  /**
   * <code>string uetr = 1[json_name = "uetr"];</code>
   * @return The bytes for uetr.
   */
  com.google.protobuf.ByteString
      getUetrBytes();

  /**
   * <code>string sender_bank = 2[json_name = "senderBank"];</code>
   * @return The senderBank.
   */
  java.lang.String getSenderBank();
  /**
   * <code>string sender_bank = 2[json_name = "senderBank"];</code>
   * @return The bytes for senderBank.
   */
  com.google.protobuf.ByteString
      getSenderBankBytes();

  /**
   * <code>string reason = 3[json_name = "reason"];</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 3[json_name = "reason"];</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();
}
