// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: switching.proto

package com.switching.v1;

public interface ConfirmPaymentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:switching.v1.ConfirmPaymentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uetr = 1[json_name = "uetr"];</code>
   * @return The uetr.
   */
  java.lang.String getUetr();
  /**
   * <code>string uetr = 1[json_name = "uetr"];</code>
   * @return The bytes for uetr.
   */
  com.google.protobuf.ByteString
      getUetrBytes();

  /**
   * <code>string sender_bank = 2[json_name = "senderBank"];</code>
   * @return The senderBank.
   */
  java.lang.String getSenderBank();
  /**
   * <code>string sender_bank = 2[json_name = "senderBank"];</code>
   * @return The bytes for senderBank.
   */
  com.google.protobuf.ByteString
      getSenderBankBytes();

  /**
   * <code>string receiver_bank = 3[json_name = "receiverBank"];</code>
   * @return The receiverBank.
   */
  java.lang.String getReceiverBank();
  /**
   * <code>string receiver_bank = 3[json_name = "receiverBank"];</code>
   * @return The bytes for receiverBank.
   */
  com.google.protobuf.ByteString
      getReceiverBankBytes();

  /**
   * <code>string from_bank_account = 4[json_name = "fromBankAccount"];</code>
   * @return The fromBankAccount.
   */
  java.lang.String getFromBankAccount();
  /**
   * <code>string from_bank_account = 4[json_name = "fromBankAccount"];</code>
   * @return The bytes for fromBankAccount.
   */
  com.google.protobuf.ByteString
      getFromBankAccountBytes();

  /**
   * <code>string to_bank_account = 5[json_name = "toBankAccount"];</code>
   * @return The toBankAccount.
   */
  java.lang.String getToBankAccount();
  /**
   * <code>string to_bank_account = 5[json_name = "toBankAccount"];</code>
   * @return The bytes for toBankAccount.
   */
  com.google.protobuf.ByteString
      getToBankAccountBytes();

  /**
   * <code>string tx_reference = 6[json_name = "txReference"];</code>
   * @return The txReference.
   */
  java.lang.String getTxReference();
  /**
   * <code>string tx_reference = 6[json_name = "txReference"];</code>
   * @return The bytes for txReference.
   */
  com.google.protobuf.ByteString
      getTxReferenceBytes();

  /**
   * <code>string note = 7[json_name = "note"];</code>
   * @return The note.
   */
  java.lang.String getNote();
  /**
   * <code>string note = 7[json_name = "note"];</code>
   * @return The bytes for note.
   */
  com.google.protobuf.ByteString
      getNoteBytes();
}
