// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: switching.proto

package com.switching.v1;

/**
 * Protobuf type {@code switching.v1.HoldPaymentRequest}
 */
public final class HoldPaymentRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:switching.v1.HoldPaymentRequest)
    HoldPaymentRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HoldPaymentRequest.newBuilder() to construct.
  private HoldPaymentRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HoldPaymentRequest() {
    uetr_ = "";
    senderBank_ = "";
    receiverBank_ = "";
    receiverBankCode_ = "";
    beneficiaryAccount_ = "";
    amount_ = "";
    note_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HoldPaymentRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HoldPaymentRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            uetr_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            senderBank_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            receiverBank_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            receiverBankCode_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            beneficiaryAccount_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            amount_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            note_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.switching.v1.SwitchingProto.internal_static_switching_v1_HoldPaymentRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.switching.v1.SwitchingProto.internal_static_switching_v1_HoldPaymentRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.switching.v1.HoldPaymentRequest.class, com.switching.v1.HoldPaymentRequest.Builder.class);
  }

  public static final int UETR_FIELD_NUMBER = 1;
  private volatile java.lang.Object uetr_;
  /**
   * <code>string uetr = 1[json_name = "uetr"];</code>
   * @return The uetr.
   */
  @java.lang.Override
  public java.lang.String getUetr() {
    java.lang.Object ref = uetr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uetr_ = s;
      return s;
    }
  }
  /**
   * <code>string uetr = 1[json_name = "uetr"];</code>
   * @return The bytes for uetr.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUetrBytes() {
    java.lang.Object ref = uetr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uetr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SENDER_BANK_FIELD_NUMBER = 2;
  private volatile java.lang.Object senderBank_;
  /**
   * <code>string sender_bank = 2[json_name = "senderBank"];</code>
   * @return The senderBank.
   */
  @java.lang.Override
  public java.lang.String getSenderBank() {
    java.lang.Object ref = senderBank_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      senderBank_ = s;
      return s;
    }
  }
  /**
   * <code>string sender_bank = 2[json_name = "senderBank"];</code>
   * @return The bytes for senderBank.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenderBankBytes() {
    java.lang.Object ref = senderBank_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      senderBank_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECEIVER_BANK_FIELD_NUMBER = 3;
  private volatile java.lang.Object receiverBank_;
  /**
   * <code>string receiver_bank = 3[json_name = "receiverBank"];</code>
   * @return The receiverBank.
   */
  @java.lang.Override
  public java.lang.String getReceiverBank() {
    java.lang.Object ref = receiverBank_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      receiverBank_ = s;
      return s;
    }
  }
  /**
   * <code>string receiver_bank = 3[json_name = "receiverBank"];</code>
   * @return The bytes for receiverBank.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReceiverBankBytes() {
    java.lang.Object ref = receiverBank_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      receiverBank_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECEIVER_BANK_CODE_FIELD_NUMBER = 4;
  private volatile java.lang.Object receiverBankCode_;
  /**
   * <code>string receiver_bank_code = 4[json_name = "receiverBankCode"];</code>
   * @return The receiverBankCode.
   */
  @java.lang.Override
  public java.lang.String getReceiverBankCode() {
    java.lang.Object ref = receiverBankCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      receiverBankCode_ = s;
      return s;
    }
  }
  /**
   * <code>string receiver_bank_code = 4[json_name = "receiverBankCode"];</code>
   * @return The bytes for receiverBankCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReceiverBankCodeBytes() {
    java.lang.Object ref = receiverBankCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      receiverBankCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BENEFICIARY_ACCOUNT_FIELD_NUMBER = 5;
  private volatile java.lang.Object beneficiaryAccount_;
  /**
   * <code>string beneficiary_account = 5[json_name = "beneficiaryAccount"];</code>
   * @return The beneficiaryAccount.
   */
  @java.lang.Override
  public java.lang.String getBeneficiaryAccount() {
    java.lang.Object ref = beneficiaryAccount_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      beneficiaryAccount_ = s;
      return s;
    }
  }
  /**
   * <code>string beneficiary_account = 5[json_name = "beneficiaryAccount"];</code>
   * @return The bytes for beneficiaryAccount.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBeneficiaryAccountBytes() {
    java.lang.Object ref = beneficiaryAccount_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      beneficiaryAccount_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AMOUNT_FIELD_NUMBER = 6;
  private volatile java.lang.Object amount_;
  /**
   * <code>string amount = 6[json_name = "amount"];</code>
   * @return The amount.
   */
  @java.lang.Override
  public java.lang.String getAmount() {
    java.lang.Object ref = amount_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      amount_ = s;
      return s;
    }
  }
  /**
   * <code>string amount = 6[json_name = "amount"];</code>
   * @return The bytes for amount.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAmountBytes() {
    java.lang.Object ref = amount_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      amount_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOTE_FIELD_NUMBER = 7;
  private volatile java.lang.Object note_;
  /**
   * <code>string note = 7[json_name = "note"];</code>
   * @return The note.
   */
  @java.lang.Override
  public java.lang.String getNote() {
    java.lang.Object ref = note_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      note_ = s;
      return s;
    }
  }
  /**
   * <code>string note = 7[json_name = "note"];</code>
   * @return The bytes for note.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNoteBytes() {
    java.lang.Object ref = note_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      note_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getUetrBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uetr_);
    }
    if (!getSenderBankBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, senderBank_);
    }
    if (!getReceiverBankBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, receiverBank_);
    }
    if (!getReceiverBankCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, receiverBankCode_);
    }
    if (!getBeneficiaryAccountBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, beneficiaryAccount_);
    }
    if (!getAmountBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, amount_);
    }
    if (!getNoteBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, note_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUetrBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uetr_);
    }
    if (!getSenderBankBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, senderBank_);
    }
    if (!getReceiverBankBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, receiverBank_);
    }
    if (!getReceiverBankCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, receiverBankCode_);
    }
    if (!getBeneficiaryAccountBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, beneficiaryAccount_);
    }
    if (!getAmountBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, amount_);
    }
    if (!getNoteBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, note_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.switching.v1.HoldPaymentRequest)) {
      return super.equals(obj);
    }
    com.switching.v1.HoldPaymentRequest other = (com.switching.v1.HoldPaymentRequest) obj;

    if (!getUetr()
        .equals(other.getUetr())) return false;
    if (!getSenderBank()
        .equals(other.getSenderBank())) return false;
    if (!getReceiverBank()
        .equals(other.getReceiverBank())) return false;
    if (!getReceiverBankCode()
        .equals(other.getReceiverBankCode())) return false;
    if (!getBeneficiaryAccount()
        .equals(other.getBeneficiaryAccount())) return false;
    if (!getAmount()
        .equals(other.getAmount())) return false;
    if (!getNote()
        .equals(other.getNote())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UETR_FIELD_NUMBER;
    hash = (53 * hash) + getUetr().hashCode();
    hash = (37 * hash) + SENDER_BANK_FIELD_NUMBER;
    hash = (53 * hash) + getSenderBank().hashCode();
    hash = (37 * hash) + RECEIVER_BANK_FIELD_NUMBER;
    hash = (53 * hash) + getReceiverBank().hashCode();
    hash = (37 * hash) + RECEIVER_BANK_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getReceiverBankCode().hashCode();
    hash = (37 * hash) + BENEFICIARY_ACCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getBeneficiaryAccount().hashCode();
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getAmount().hashCode();
    hash = (37 * hash) + NOTE_FIELD_NUMBER;
    hash = (53 * hash) + getNote().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.switching.v1.HoldPaymentRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.switching.v1.HoldPaymentRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.switching.v1.HoldPaymentRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.switching.v1.HoldPaymentRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.switching.v1.HoldPaymentRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.switching.v1.HoldPaymentRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.switching.v1.HoldPaymentRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.switching.v1.HoldPaymentRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.switching.v1.HoldPaymentRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.switching.v1.HoldPaymentRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.switching.v1.HoldPaymentRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.switching.v1.HoldPaymentRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.switching.v1.HoldPaymentRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code switching.v1.HoldPaymentRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:switching.v1.HoldPaymentRequest)
      com.switching.v1.HoldPaymentRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.switching.v1.SwitchingProto.internal_static_switching_v1_HoldPaymentRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.switching.v1.SwitchingProto.internal_static_switching_v1_HoldPaymentRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.switching.v1.HoldPaymentRequest.class, com.switching.v1.HoldPaymentRequest.Builder.class);
    }

    // Construct using com.switching.v1.HoldPaymentRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      uetr_ = "";

      senderBank_ = "";

      receiverBank_ = "";

      receiverBankCode_ = "";

      beneficiaryAccount_ = "";

      amount_ = "";

      note_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.switching.v1.SwitchingProto.internal_static_switching_v1_HoldPaymentRequest_descriptor;
    }

    @java.lang.Override
    public com.switching.v1.HoldPaymentRequest getDefaultInstanceForType() {
      return com.switching.v1.HoldPaymentRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.switching.v1.HoldPaymentRequest build() {
      com.switching.v1.HoldPaymentRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.switching.v1.HoldPaymentRequest buildPartial() {
      com.switching.v1.HoldPaymentRequest result = new com.switching.v1.HoldPaymentRequest(this);
      result.uetr_ = uetr_;
      result.senderBank_ = senderBank_;
      result.receiverBank_ = receiverBank_;
      result.receiverBankCode_ = receiverBankCode_;
      result.beneficiaryAccount_ = beneficiaryAccount_;
      result.amount_ = amount_;
      result.note_ = note_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.switching.v1.HoldPaymentRequest) {
        return mergeFrom((com.switching.v1.HoldPaymentRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.switching.v1.HoldPaymentRequest other) {
      if (other == com.switching.v1.HoldPaymentRequest.getDefaultInstance()) return this;
      if (!other.getUetr().isEmpty()) {
        uetr_ = other.uetr_;
        onChanged();
      }
      if (!other.getSenderBank().isEmpty()) {
        senderBank_ = other.senderBank_;
        onChanged();
      }
      if (!other.getReceiverBank().isEmpty()) {
        receiverBank_ = other.receiverBank_;
        onChanged();
      }
      if (!other.getReceiverBankCode().isEmpty()) {
        receiverBankCode_ = other.receiverBankCode_;
        onChanged();
      }
      if (!other.getBeneficiaryAccount().isEmpty()) {
        beneficiaryAccount_ = other.beneficiaryAccount_;
        onChanged();
      }
      if (!other.getAmount().isEmpty()) {
        amount_ = other.amount_;
        onChanged();
      }
      if (!other.getNote().isEmpty()) {
        note_ = other.note_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.switching.v1.HoldPaymentRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.switching.v1.HoldPaymentRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object uetr_ = "";
    /**
     * <code>string uetr = 1[json_name = "uetr"];</code>
     * @return The uetr.
     */
    public java.lang.String getUetr() {
      java.lang.Object ref = uetr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uetr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string uetr = 1[json_name = "uetr"];</code>
     * @return The bytes for uetr.
     */
    public com.google.protobuf.ByteString
        getUetrBytes() {
      java.lang.Object ref = uetr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uetr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string uetr = 1[json_name = "uetr"];</code>
     * @param value The uetr to set.
     * @return This builder for chaining.
     */
    public Builder setUetr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      uetr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string uetr = 1[json_name = "uetr"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUetr() {
      
      uetr_ = getDefaultInstance().getUetr();
      onChanged();
      return this;
    }
    /**
     * <code>string uetr = 1[json_name = "uetr"];</code>
     * @param value The bytes for uetr to set.
     * @return This builder for chaining.
     */
    public Builder setUetrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      uetr_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object senderBank_ = "";
    /**
     * <code>string sender_bank = 2[json_name = "senderBank"];</code>
     * @return The senderBank.
     */
    public java.lang.String getSenderBank() {
      java.lang.Object ref = senderBank_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderBank_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sender_bank = 2[json_name = "senderBank"];</code>
     * @return The bytes for senderBank.
     */
    public com.google.protobuf.ByteString
        getSenderBankBytes() {
      java.lang.Object ref = senderBank_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderBank_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sender_bank = 2[json_name = "senderBank"];</code>
     * @param value The senderBank to set.
     * @return This builder for chaining.
     */
    public Builder setSenderBank(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      senderBank_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sender_bank = 2[json_name = "senderBank"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderBank() {
      
      senderBank_ = getDefaultInstance().getSenderBank();
      onChanged();
      return this;
    }
    /**
     * <code>string sender_bank = 2[json_name = "senderBank"];</code>
     * @param value The bytes for senderBank to set.
     * @return This builder for chaining.
     */
    public Builder setSenderBankBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      senderBank_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object receiverBank_ = "";
    /**
     * <code>string receiver_bank = 3[json_name = "receiverBank"];</code>
     * @return The receiverBank.
     */
    public java.lang.String getReceiverBank() {
      java.lang.Object ref = receiverBank_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiverBank_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string receiver_bank = 3[json_name = "receiverBank"];</code>
     * @return The bytes for receiverBank.
     */
    public com.google.protobuf.ByteString
        getReceiverBankBytes() {
      java.lang.Object ref = receiverBank_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverBank_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string receiver_bank = 3[json_name = "receiverBank"];</code>
     * @param value The receiverBank to set.
     * @return This builder for chaining.
     */
    public Builder setReceiverBank(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      receiverBank_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string receiver_bank = 3[json_name = "receiverBank"];</code>
     * @return This builder for chaining.
     */
    public Builder clearReceiverBank() {
      
      receiverBank_ = getDefaultInstance().getReceiverBank();
      onChanged();
      return this;
    }
    /**
     * <code>string receiver_bank = 3[json_name = "receiverBank"];</code>
     * @param value The bytes for receiverBank to set.
     * @return This builder for chaining.
     */
    public Builder setReceiverBankBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      receiverBank_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object receiverBankCode_ = "";
    /**
     * <code>string receiver_bank_code = 4[json_name = "receiverBankCode"];</code>
     * @return The receiverBankCode.
     */
    public java.lang.String getReceiverBankCode() {
      java.lang.Object ref = receiverBankCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiverBankCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string receiver_bank_code = 4[json_name = "receiverBankCode"];</code>
     * @return The bytes for receiverBankCode.
     */
    public com.google.protobuf.ByteString
        getReceiverBankCodeBytes() {
      java.lang.Object ref = receiverBankCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverBankCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string receiver_bank_code = 4[json_name = "receiverBankCode"];</code>
     * @param value The receiverBankCode to set.
     * @return This builder for chaining.
     */
    public Builder setReceiverBankCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      receiverBankCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string receiver_bank_code = 4[json_name = "receiverBankCode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearReceiverBankCode() {
      
      receiverBankCode_ = getDefaultInstance().getReceiverBankCode();
      onChanged();
      return this;
    }
    /**
     * <code>string receiver_bank_code = 4[json_name = "receiverBankCode"];</code>
     * @param value The bytes for receiverBankCode to set.
     * @return This builder for chaining.
     */
    public Builder setReceiverBankCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      receiverBankCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object beneficiaryAccount_ = "";
    /**
     * <code>string beneficiary_account = 5[json_name = "beneficiaryAccount"];</code>
     * @return The beneficiaryAccount.
     */
    public java.lang.String getBeneficiaryAccount() {
      java.lang.Object ref = beneficiaryAccount_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        beneficiaryAccount_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string beneficiary_account = 5[json_name = "beneficiaryAccount"];</code>
     * @return The bytes for beneficiaryAccount.
     */
    public com.google.protobuf.ByteString
        getBeneficiaryAccountBytes() {
      java.lang.Object ref = beneficiaryAccount_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        beneficiaryAccount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string beneficiary_account = 5[json_name = "beneficiaryAccount"];</code>
     * @param value The beneficiaryAccount to set.
     * @return This builder for chaining.
     */
    public Builder setBeneficiaryAccount(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      beneficiaryAccount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string beneficiary_account = 5[json_name = "beneficiaryAccount"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBeneficiaryAccount() {
      
      beneficiaryAccount_ = getDefaultInstance().getBeneficiaryAccount();
      onChanged();
      return this;
    }
    /**
     * <code>string beneficiary_account = 5[json_name = "beneficiaryAccount"];</code>
     * @param value The bytes for beneficiaryAccount to set.
     * @return This builder for chaining.
     */
    public Builder setBeneficiaryAccountBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      beneficiaryAccount_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object amount_ = "";
    /**
     * <code>string amount = 6[json_name = "amount"];</code>
     * @return The amount.
     */
    public java.lang.String getAmount() {
      java.lang.Object ref = amount_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        amount_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string amount = 6[json_name = "amount"];</code>
     * @return The bytes for amount.
     */
    public com.google.protobuf.ByteString
        getAmountBytes() {
      java.lang.Object ref = amount_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        amount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string amount = 6[json_name = "amount"];</code>
     * @param value The amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmount(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      amount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string amount = 6[json_name = "amount"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAmount() {
      
      amount_ = getDefaultInstance().getAmount();
      onChanged();
      return this;
    }
    /**
     * <code>string amount = 6[json_name = "amount"];</code>
     * @param value The bytes for amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmountBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      amount_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object note_ = "";
    /**
     * <code>string note = 7[json_name = "note"];</code>
     * @return The note.
     */
    public java.lang.String getNote() {
      java.lang.Object ref = note_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        note_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string note = 7[json_name = "note"];</code>
     * @return The bytes for note.
     */
    public com.google.protobuf.ByteString
        getNoteBytes() {
      java.lang.Object ref = note_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        note_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string note = 7[json_name = "note"];</code>
     * @param value The note to set.
     * @return This builder for chaining.
     */
    public Builder setNote(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      note_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string note = 7[json_name = "note"];</code>
     * @return This builder for chaining.
     */
    public Builder clearNote() {
      
      note_ = getDefaultInstance().getNote();
      onChanged();
      return this;
    }
    /**
     * <code>string note = 7[json_name = "note"];</code>
     * @param value The bytes for note to set.
     * @return This builder for chaining.
     */
    public Builder setNoteBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      note_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:switching.v1.HoldPaymentRequest)
  }

  // @@protoc_insertion_point(class_scope:switching.v1.HoldPaymentRequest)
  private static final com.switching.v1.HoldPaymentRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.switching.v1.HoldPaymentRequest();
  }

  public static com.switching.v1.HoldPaymentRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HoldPaymentRequest>
      PARSER = new com.google.protobuf.AbstractParser<HoldPaymentRequest>() {
    @java.lang.Override
    public HoldPaymentRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HoldPaymentRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HoldPaymentRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HoldPaymentRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.switching.v1.HoldPaymentRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

