// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: switching.proto

package com.switching.v1;

/**
 * Protobuf type {@code switching.v1.HoldBatchPaymentRequest}
 */
public final class HoldBatchPaymentRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:switching.v1.HoldBatchPaymentRequest)
    HoldBatchPaymentRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HoldBatchPaymentRequest.newBuilder() to construct.
  private HoldBatchPaymentRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HoldBatchPaymentRequest() {
    senderBank_ = "";
    items_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HoldBatchPaymentRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HoldBatchPaymentRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            senderBank_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              items_ = new java.util.ArrayList<com.switching.v1.HoldPaymentItem>();
              mutable_bitField0_ |= 0x00000001;
            }
            items_.add(
                input.readMessage(com.switching.v1.HoldPaymentItem.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        items_ = java.util.Collections.unmodifiableList(items_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.switching.v1.SwitchingProto.internal_static_switching_v1_HoldBatchPaymentRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.switching.v1.SwitchingProto.internal_static_switching_v1_HoldBatchPaymentRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.switching.v1.HoldBatchPaymentRequest.class, com.switching.v1.HoldBatchPaymentRequest.Builder.class);
  }

  public static final int SENDER_BANK_FIELD_NUMBER = 1;
  private volatile java.lang.Object senderBank_;
  /**
   * <code>string sender_bank = 1[json_name = "senderBank"];</code>
   * @return The senderBank.
   */
  @java.lang.Override
  public java.lang.String getSenderBank() {
    java.lang.Object ref = senderBank_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      senderBank_ = s;
      return s;
    }
  }
  /**
   * <code>string sender_bank = 1[json_name = "senderBank"];</code>
   * @return The bytes for senderBank.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenderBankBytes() {
    java.lang.Object ref = senderBank_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      senderBank_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ITEMS_FIELD_NUMBER = 2;
  private java.util.List<com.switching.v1.HoldPaymentItem> items_;
  /**
   * <code>repeated .switching.v1.HoldPaymentItem items = 2[json_name = "items"];</code>
   */
  @java.lang.Override
  public java.util.List<com.switching.v1.HoldPaymentItem> getItemsList() {
    return items_;
  }
  /**
   * <code>repeated .switching.v1.HoldPaymentItem items = 2[json_name = "items"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.switching.v1.HoldPaymentItemOrBuilder> 
      getItemsOrBuilderList() {
    return items_;
  }
  /**
   * <code>repeated .switching.v1.HoldPaymentItem items = 2[json_name = "items"];</code>
   */
  @java.lang.Override
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <code>repeated .switching.v1.HoldPaymentItem items = 2[json_name = "items"];</code>
   */
  @java.lang.Override
  public com.switching.v1.HoldPaymentItem getItems(int index) {
    return items_.get(index);
  }
  /**
   * <code>repeated .switching.v1.HoldPaymentItem items = 2[json_name = "items"];</code>
   */
  @java.lang.Override
  public com.switching.v1.HoldPaymentItemOrBuilder getItemsOrBuilder(
      int index) {
    return items_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSenderBankBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, senderBank_);
    }
    for (int i = 0; i < items_.size(); i++) {
      output.writeMessage(2, items_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSenderBankBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, senderBank_);
    }
    for (int i = 0; i < items_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, items_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.switching.v1.HoldBatchPaymentRequest)) {
      return super.equals(obj);
    }
    com.switching.v1.HoldBatchPaymentRequest other = (com.switching.v1.HoldBatchPaymentRequest) obj;

    if (!getSenderBank()
        .equals(other.getSenderBank())) return false;
    if (!getItemsList()
        .equals(other.getItemsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SENDER_BANK_FIELD_NUMBER;
    hash = (53 * hash) + getSenderBank().hashCode();
    if (getItemsCount() > 0) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getItemsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.switching.v1.HoldBatchPaymentRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.switching.v1.HoldBatchPaymentRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.switching.v1.HoldBatchPaymentRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.switching.v1.HoldBatchPaymentRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.switching.v1.HoldBatchPaymentRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.switching.v1.HoldBatchPaymentRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.switching.v1.HoldBatchPaymentRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.switching.v1.HoldBatchPaymentRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.switching.v1.HoldBatchPaymentRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.switching.v1.HoldBatchPaymentRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.switching.v1.HoldBatchPaymentRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.switching.v1.HoldBatchPaymentRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.switching.v1.HoldBatchPaymentRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code switching.v1.HoldBatchPaymentRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:switching.v1.HoldBatchPaymentRequest)
      com.switching.v1.HoldBatchPaymentRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.switching.v1.SwitchingProto.internal_static_switching_v1_HoldBatchPaymentRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.switching.v1.SwitchingProto.internal_static_switching_v1_HoldBatchPaymentRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.switching.v1.HoldBatchPaymentRequest.class, com.switching.v1.HoldBatchPaymentRequest.Builder.class);
    }

    // Construct using com.switching.v1.HoldBatchPaymentRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getItemsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      senderBank_ = "";

      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.switching.v1.SwitchingProto.internal_static_switching_v1_HoldBatchPaymentRequest_descriptor;
    }

    @java.lang.Override
    public com.switching.v1.HoldBatchPaymentRequest getDefaultInstanceForType() {
      return com.switching.v1.HoldBatchPaymentRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.switching.v1.HoldBatchPaymentRequest build() {
      com.switching.v1.HoldBatchPaymentRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.switching.v1.HoldBatchPaymentRequest buildPartial() {
      com.switching.v1.HoldBatchPaymentRequest result = new com.switching.v1.HoldBatchPaymentRequest(this);
      int from_bitField0_ = bitField0_;
      result.senderBank_ = senderBank_;
      if (itemsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          items_ = java.util.Collections.unmodifiableList(items_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.items_ = items_;
      } else {
        result.items_ = itemsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.switching.v1.HoldBatchPaymentRequest) {
        return mergeFrom((com.switching.v1.HoldBatchPaymentRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.switching.v1.HoldBatchPaymentRequest other) {
      if (other == com.switching.v1.HoldBatchPaymentRequest.getDefaultInstance()) return this;
      if (!other.getSenderBank().isEmpty()) {
        senderBank_ = other.senderBank_;
        onChanged();
      }
      if (itemsBuilder_ == null) {
        if (!other.items_.isEmpty()) {
          if (items_.isEmpty()) {
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureItemsIsMutable();
            items_.addAll(other.items_);
          }
          onChanged();
        }
      } else {
        if (!other.items_.isEmpty()) {
          if (itemsBuilder_.isEmpty()) {
            itemsBuilder_.dispose();
            itemsBuilder_ = null;
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
            itemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getItemsFieldBuilder() : null;
          } else {
            itemsBuilder_.addAllMessages(other.items_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.switching.v1.HoldBatchPaymentRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.switching.v1.HoldBatchPaymentRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object senderBank_ = "";
    /**
     * <code>string sender_bank = 1[json_name = "senderBank"];</code>
     * @return The senderBank.
     */
    public java.lang.String getSenderBank() {
      java.lang.Object ref = senderBank_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderBank_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sender_bank = 1[json_name = "senderBank"];</code>
     * @return The bytes for senderBank.
     */
    public com.google.protobuf.ByteString
        getSenderBankBytes() {
      java.lang.Object ref = senderBank_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderBank_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sender_bank = 1[json_name = "senderBank"];</code>
     * @param value The senderBank to set.
     * @return This builder for chaining.
     */
    public Builder setSenderBank(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      senderBank_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sender_bank = 1[json_name = "senderBank"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderBank() {
      
      senderBank_ = getDefaultInstance().getSenderBank();
      onChanged();
      return this;
    }
    /**
     * <code>string sender_bank = 1[json_name = "senderBank"];</code>
     * @param value The bytes for senderBank to set.
     * @return This builder for chaining.
     */
    public Builder setSenderBankBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      senderBank_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.switching.v1.HoldPaymentItem> items_ =
      java.util.Collections.emptyList();
    private void ensureItemsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        items_ = new java.util.ArrayList<com.switching.v1.HoldPaymentItem>(items_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.switching.v1.HoldPaymentItem, com.switching.v1.HoldPaymentItem.Builder, com.switching.v1.HoldPaymentItemOrBuilder> itemsBuilder_;

    /**
     * <code>repeated .switching.v1.HoldPaymentItem items = 2[json_name = "items"];</code>
     */
    public java.util.List<com.switching.v1.HoldPaymentItem> getItemsList() {
      if (itemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(items_);
      } else {
        return itemsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .switching.v1.HoldPaymentItem items = 2[json_name = "items"];</code>
     */
    public int getItemsCount() {
      if (itemsBuilder_ == null) {
        return items_.size();
      } else {
        return itemsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .switching.v1.HoldPaymentItem items = 2[json_name = "items"];</code>
     */
    public com.switching.v1.HoldPaymentItem getItems(int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);
      } else {
        return itemsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .switching.v1.HoldPaymentItem items = 2[json_name = "items"];</code>
     */
    public Builder setItems(
        int index, com.switching.v1.HoldPaymentItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.set(index, value);
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .switching.v1.HoldPaymentItem items = 2[json_name = "items"];</code>
     */
    public Builder setItems(
        int index, com.switching.v1.HoldPaymentItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.set(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .switching.v1.HoldPaymentItem items = 2[json_name = "items"];</code>
     */
    public Builder addItems(com.switching.v1.HoldPaymentItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .switching.v1.HoldPaymentItem items = 2[json_name = "items"];</code>
     */
    public Builder addItems(
        int index, com.switching.v1.HoldPaymentItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(index, value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .switching.v1.HoldPaymentItem items = 2[json_name = "items"];</code>
     */
    public Builder addItems(
        com.switching.v1.HoldPaymentItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .switching.v1.HoldPaymentItem items = 2[json_name = "items"];</code>
     */
    public Builder addItems(
        int index, com.switching.v1.HoldPaymentItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .switching.v1.HoldPaymentItem items = 2[json_name = "items"];</code>
     */
    public Builder addAllItems(
        java.lang.Iterable<? extends com.switching.v1.HoldPaymentItem> values) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, items_);
        onChanged();
      } else {
        itemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .switching.v1.HoldPaymentItem items = 2[json_name = "items"];</code>
     */
    public Builder clearItems() {
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .switching.v1.HoldPaymentItem items = 2[json_name = "items"];</code>
     */
    public Builder removeItems(int index) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.remove(index);
        onChanged();
      } else {
        itemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .switching.v1.HoldPaymentItem items = 2[json_name = "items"];</code>
     */
    public com.switching.v1.HoldPaymentItem.Builder getItemsBuilder(
        int index) {
      return getItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .switching.v1.HoldPaymentItem items = 2[json_name = "items"];</code>
     */
    public com.switching.v1.HoldPaymentItemOrBuilder getItemsOrBuilder(
        int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);  } else {
        return itemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .switching.v1.HoldPaymentItem items = 2[json_name = "items"];</code>
     */
    public java.util.List<? extends com.switching.v1.HoldPaymentItemOrBuilder> 
         getItemsOrBuilderList() {
      if (itemsBuilder_ != null) {
        return itemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(items_);
      }
    }
    /**
     * <code>repeated .switching.v1.HoldPaymentItem items = 2[json_name = "items"];</code>
     */
    public com.switching.v1.HoldPaymentItem.Builder addItemsBuilder() {
      return getItemsFieldBuilder().addBuilder(
          com.switching.v1.HoldPaymentItem.getDefaultInstance());
    }
    /**
     * <code>repeated .switching.v1.HoldPaymentItem items = 2[json_name = "items"];</code>
     */
    public com.switching.v1.HoldPaymentItem.Builder addItemsBuilder(
        int index) {
      return getItemsFieldBuilder().addBuilder(
          index, com.switching.v1.HoldPaymentItem.getDefaultInstance());
    }
    /**
     * <code>repeated .switching.v1.HoldPaymentItem items = 2[json_name = "items"];</code>
     */
    public java.util.List<com.switching.v1.HoldPaymentItem.Builder> 
         getItemsBuilderList() {
      return getItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.switching.v1.HoldPaymentItem, com.switching.v1.HoldPaymentItem.Builder, com.switching.v1.HoldPaymentItemOrBuilder> 
        getItemsFieldBuilder() {
      if (itemsBuilder_ == null) {
        itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.switching.v1.HoldPaymentItem, com.switching.v1.HoldPaymentItem.Builder, com.switching.v1.HoldPaymentItemOrBuilder>(
                items_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        items_ = null;
      }
      return itemsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:switching.v1.HoldBatchPaymentRequest)
  }

  // @@protoc_insertion_point(class_scope:switching.v1.HoldBatchPaymentRequest)
  private static final com.switching.v1.HoldBatchPaymentRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.switching.v1.HoldBatchPaymentRequest();
  }

  public static com.switching.v1.HoldBatchPaymentRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HoldBatchPaymentRequest>
      PARSER = new com.google.protobuf.AbstractParser<HoldBatchPaymentRequest>() {
    @java.lang.Override
    public HoldBatchPaymentRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HoldBatchPaymentRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HoldBatchPaymentRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HoldBatchPaymentRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.switching.v1.HoldBatchPaymentRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

