// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: switching.proto

package com.switching.v1;

public interface PaymentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:switching.v1.PaymentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tx_hash = 1[json_name = "txHash"];</code>
   * @return The txHash.
   */
  java.lang.String getTxHash();
  /**
   * <code>string tx_hash = 1[json_name = "txHash"];</code>
   * @return The bytes for txHash.
   */
  com.google.protobuf.ByteString
      getTxHashBytes();

  /**
   * <code>string ref_id = 2[json_name = "refId"];</code>
   * @return The refId.
   */
  java.lang.String getRefId();
  /**
   * <code>string ref_id = 2[json_name = "refId"];</code>
   * @return The bytes for refId.
   */
  com.google.protobuf.ByteString
      getRefIdBytes();

  /**
   * <code>string status = 3[json_name = "status"];</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 3[json_name = "status"];</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
