// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: switching.proto

package com.switching.v1;

public interface QueryBalanceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:switching.v1.QueryBalanceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bank_address = 1[json_name = "bankAddress"];</code>
   * @return The bankAddress.
   */
  java.lang.String getBankAddress();
  /**
   * <code>string bank_address = 1[json_name = "bankAddress"];</code>
   * @return The bytes for bankAddress.
   */
  com.google.protobuf.ByteString
      getBankAddressBytes();
}
