// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: switching.proto

package com.switching.v1;

public interface RegisterBankRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:switching.v1.RegisterBankRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bank_code = 1[json_name = "bankCode"];</code>
   * @return The bankCode.
   */
  java.lang.String getBankCode();
  /**
   * <code>string bank_code = 1[json_name = "bankCode"];</code>
   * @return The bytes for bankCode.
   */
  com.google.protobuf.ByteString
      getBankCodeBytes();
}
