// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: access-point/fi.proto

package accesspoint

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FiService_CreateTransfer_FullMethodName    = "/accesspoint.v1.FiService/CreateTransfer"
	FiService_GetTransfer_FullMethodName       = "/accesspoint.v1.FiService/GetTransfer"
	FiService_GetTransferStatus_FullMethodName = "/accesspoint.v1.FiService/GetTransferStatus"
	FiService_ConfirmTransfer_FullMethodName   = "/accesspoint.v1.FiService/ConfirmTransfer"
	FiService_SearchTransfers_FullMethodName   = "/accesspoint.v1.FiService/SearchTransfers"
	FiService_BulkTransfer_FullMethodName      = "/accesspoint.v1.FiService/BulkTransfer"
)

// FiServiceClient is the client API for FiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FiServiceClient interface {
	CreateTransfer(ctx context.Context, in *CreateTransferRequest, opts ...grpc.CallOption) (*CreateTransferResponse, error)
	GetTransfer(ctx context.Context, in *GetTransferRequest, opts ...grpc.CallOption) (*Transfer, error)
	GetTransferStatus(ctx context.Context, in *GetTransferRequest, opts ...grpc.CallOption) (*TransferStatus, error)
	ConfirmTransfer(ctx context.Context, in *ConfirmTransferRequest, opts ...grpc.CallOption) (*ConfirmTransferResponse, error)
	SearchTransfers(ctx context.Context, in *SearchTransfersRequest, opts ...grpc.CallOption) (*SearchTransfersResponse, error)
	BulkTransfer(ctx context.Context, in *BulkTransferRequest, opts ...grpc.CallOption) (*BulkTransferResponse, error)
}

type fiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFiServiceClient(cc grpc.ClientConnInterface) FiServiceClient {
	return &fiServiceClient{cc}
}

func (c *fiServiceClient) CreateTransfer(ctx context.Context, in *CreateTransferRequest, opts ...grpc.CallOption) (*CreateTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTransferResponse)
	err := c.cc.Invoke(ctx, FiService_CreateTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fiServiceClient) GetTransfer(ctx context.Context, in *GetTransferRequest, opts ...grpc.CallOption) (*Transfer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Transfer)
	err := c.cc.Invoke(ctx, FiService_GetTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fiServiceClient) GetTransferStatus(ctx context.Context, in *GetTransferRequest, opts ...grpc.CallOption) (*TransferStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferStatus)
	err := c.cc.Invoke(ctx, FiService_GetTransferStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fiServiceClient) ConfirmTransfer(ctx context.Context, in *ConfirmTransferRequest, opts ...grpc.CallOption) (*ConfirmTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmTransferResponse)
	err := c.cc.Invoke(ctx, FiService_ConfirmTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fiServiceClient) SearchTransfers(ctx context.Context, in *SearchTransfersRequest, opts ...grpc.CallOption) (*SearchTransfersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchTransfersResponse)
	err := c.cc.Invoke(ctx, FiService_SearchTransfers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fiServiceClient) BulkTransfer(ctx context.Context, in *BulkTransferRequest, opts ...grpc.CallOption) (*BulkTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkTransferResponse)
	err := c.cc.Invoke(ctx, FiService_BulkTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FiServiceServer is the server API for FiService service.
// All implementations must embed UnimplementedFiServiceServer
// for forward compatibility.
type FiServiceServer interface {
	CreateTransfer(context.Context, *CreateTransferRequest) (*CreateTransferResponse, error)
	GetTransfer(context.Context, *GetTransferRequest) (*Transfer, error)
	GetTransferStatus(context.Context, *GetTransferRequest) (*TransferStatus, error)
	ConfirmTransfer(context.Context, *ConfirmTransferRequest) (*ConfirmTransferResponse, error)
	SearchTransfers(context.Context, *SearchTransfersRequest) (*SearchTransfersResponse, error)
	BulkTransfer(context.Context, *BulkTransferRequest) (*BulkTransferResponse, error)
	mustEmbedUnimplementedFiServiceServer()
}

// UnimplementedFiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFiServiceServer struct{}

func (UnimplementedFiServiceServer) CreateTransfer(context.Context, *CreateTransferRequest) (*CreateTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTransfer not implemented")
}
func (UnimplementedFiServiceServer) GetTransfer(context.Context, *GetTransferRequest) (*Transfer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransfer not implemented")
}
func (UnimplementedFiServiceServer) GetTransferStatus(context.Context, *GetTransferRequest) (*TransferStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransferStatus not implemented")
}
func (UnimplementedFiServiceServer) ConfirmTransfer(context.Context, *ConfirmTransferRequest) (*ConfirmTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmTransfer not implemented")
}
func (UnimplementedFiServiceServer) SearchTransfers(context.Context, *SearchTransfersRequest) (*SearchTransfersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchTransfers not implemented")
}
func (UnimplementedFiServiceServer) BulkTransfer(context.Context, *BulkTransferRequest) (*BulkTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkTransfer not implemented")
}
func (UnimplementedFiServiceServer) mustEmbedUnimplementedFiServiceServer() {}
func (UnimplementedFiServiceServer) testEmbeddedByValue()                   {}

// UnsafeFiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FiServiceServer will
// result in compilation errors.
type UnsafeFiServiceServer interface {
	mustEmbedUnimplementedFiServiceServer()
}

func RegisterFiServiceServer(s grpc.ServiceRegistrar, srv FiServiceServer) {
	// If the following call pancis, it indicates UnimplementedFiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FiService_ServiceDesc, srv)
}

func _FiService_CreateTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FiServiceServer).CreateTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FiService_CreateTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FiServiceServer).CreateTransfer(ctx, req.(*CreateTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FiService_GetTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FiServiceServer).GetTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FiService_GetTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FiServiceServer).GetTransfer(ctx, req.(*GetTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FiService_GetTransferStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FiServiceServer).GetTransferStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FiService_GetTransferStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FiServiceServer).GetTransferStatus(ctx, req.(*GetTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FiService_ConfirmTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FiServiceServer).ConfirmTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FiService_ConfirmTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FiServiceServer).ConfirmTransfer(ctx, req.(*ConfirmTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FiService_SearchTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FiServiceServer).SearchTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FiService_SearchTransfers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FiServiceServer).SearchTransfers(ctx, req.(*SearchTransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FiService_BulkTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FiServiceServer).BulkTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FiService_BulkTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FiServiceServer).BulkTransfer(ctx, req.(*BulkTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FiService_ServiceDesc is the grpc.ServiceDesc for FiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accesspoint.v1.FiService",
	HandlerType: (*FiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTransfer",
			Handler:    _FiService_CreateTransfer_Handler,
		},
		{
			MethodName: "GetTransfer",
			Handler:    _FiService_GetTransfer_Handler,
		},
		{
			MethodName: "GetTransferStatus",
			Handler:    _FiService_GetTransferStatus_Handler,
		},
		{
			MethodName: "ConfirmTransfer",
			Handler:    _FiService_ConfirmTransfer_Handler,
		},
		{
			MethodName: "SearchTransfers",
			Handler:    _FiService_SearchTransfers_Handler,
		},
		{
			MethodName: "BulkTransfer",
			Handler:    _FiService_BulkTransfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "access-point/fi.proto",
}
