// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: access-point/kyc.proto

// Package định nghĩa các message và service cho KYC (Know Your Customer) trong access point

package accesspoint

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KycService_ListEntities_FullMethodName       = "/accesspoint.v1.KycService/ListEntities"
	KycService_GetEntity_FullMethodName          = "/accesspoint.v1.KycService/GetEntity"
	KycService_GetEntityDocuments_FullMethodName = "/accesspoint.v1.KycService/GetEntityDocuments"
	KycService_SubmitKyc_FullMethodName          = "/accesspoint.v1.KycService/SubmitKyc"
	KycService_Metadata_FullMethodName           = "/accesspoint.v1.KycService/Metadata"
	KycService_Audit_FullMethodName              = "/accesspoint.v1.KycService/Audit"
)

// KycServiceClient is the client API for KycService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service quản lý KYC (Know Your Customer) - xác minh khách hàng
type KycServiceClient interface {
	// Lấy danh sách tất cả các thực thể KYC
	ListEntities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListEntitiesResponse, error)
	// Lấy thông tin chi tiết của một thực thể KYC
	GetEntity(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*KycEntity, error)
	// Lấy danh sách tài liệu của một thực thể KYC
	GetEntityDocuments(ctx context.Context, in *GetEntityDocsRequest, opts ...grpc.CallOption) (*GetEntityDocsResponse, error)
	// Gửi thông tin KYC để xác minh
	SubmitKyc(ctx context.Context, in *SubmitKycRequest, opts ...grpc.CallOption) (*SubmitKycResponse, error)
	// Lấy metadata về các trường KYC được hỗ trợ
	Metadata(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*KycMetadata, error)
	// Lấy lịch sử audit (kiểm tra) của một thực thể KYC
	Audit(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*AuditResponse, error)
}

type kycServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKycServiceClient(cc grpc.ClientConnInterface) KycServiceClient {
	return &kycServiceClient{cc}
}

func (c *kycServiceClient) ListEntities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListEntitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEntitiesResponse)
	err := c.cc.Invoke(ctx, KycService_ListEntities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kycServiceClient) GetEntity(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*KycEntity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KycEntity)
	err := c.cc.Invoke(ctx, KycService_GetEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kycServiceClient) GetEntityDocuments(ctx context.Context, in *GetEntityDocsRequest, opts ...grpc.CallOption) (*GetEntityDocsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEntityDocsResponse)
	err := c.cc.Invoke(ctx, KycService_GetEntityDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kycServiceClient) SubmitKyc(ctx context.Context, in *SubmitKycRequest, opts ...grpc.CallOption) (*SubmitKycResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitKycResponse)
	err := c.cc.Invoke(ctx, KycService_SubmitKyc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kycServiceClient) Metadata(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*KycMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KycMetadata)
	err := c.cc.Invoke(ctx, KycService_Metadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kycServiceClient) Audit(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*AuditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditResponse)
	err := c.cc.Invoke(ctx, KycService_Audit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KycServiceServer is the server API for KycService service.
// All implementations must embed UnimplementedKycServiceServer
// for forward compatibility.
//
// Service quản lý KYC (Know Your Customer) - xác minh khách hàng
type KycServiceServer interface {
	// Lấy danh sách tất cả các thực thể KYC
	ListEntities(context.Context, *Empty) (*ListEntitiesResponse, error)
	// Lấy thông tin chi tiết của một thực thể KYC
	GetEntity(context.Context, *GetEntityRequest) (*KycEntity, error)
	// Lấy danh sách tài liệu của một thực thể KYC
	GetEntityDocuments(context.Context, *GetEntityDocsRequest) (*GetEntityDocsResponse, error)
	// Gửi thông tin KYC để xác minh
	SubmitKyc(context.Context, *SubmitKycRequest) (*SubmitKycResponse, error)
	// Lấy metadata về các trường KYC được hỗ trợ
	Metadata(context.Context, *Empty) (*KycMetadata, error)
	// Lấy lịch sử audit (kiểm tra) của một thực thể KYC
	Audit(context.Context, *GetEntityRequest) (*AuditResponse, error)
	mustEmbedUnimplementedKycServiceServer()
}

// UnimplementedKycServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKycServiceServer struct{}

func (UnimplementedKycServiceServer) ListEntities(context.Context, *Empty) (*ListEntitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEntities not implemented")
}
func (UnimplementedKycServiceServer) GetEntity(context.Context, *GetEntityRequest) (*KycEntity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEntity not implemented")
}
func (UnimplementedKycServiceServer) GetEntityDocuments(context.Context, *GetEntityDocsRequest) (*GetEntityDocsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEntityDocuments not implemented")
}
func (UnimplementedKycServiceServer) SubmitKyc(context.Context, *SubmitKycRequest) (*SubmitKycResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitKyc not implemented")
}
func (UnimplementedKycServiceServer) Metadata(context.Context, *Empty) (*KycMetadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Metadata not implemented")
}
func (UnimplementedKycServiceServer) Audit(context.Context, *GetEntityRequest) (*AuditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Audit not implemented")
}
func (UnimplementedKycServiceServer) mustEmbedUnimplementedKycServiceServer() {}
func (UnimplementedKycServiceServer) testEmbeddedByValue()                    {}

// UnsafeKycServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KycServiceServer will
// result in compilation errors.
type UnsafeKycServiceServer interface {
	mustEmbedUnimplementedKycServiceServer()
}

func RegisterKycServiceServer(s grpc.ServiceRegistrar, srv KycServiceServer) {
	// If the following call pancis, it indicates UnimplementedKycServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KycService_ServiceDesc, srv)
}

func _KycService_ListEntities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KycServiceServer).ListEntities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KycService_ListEntities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KycServiceServer).ListEntities(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _KycService_GetEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KycServiceServer).GetEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KycService_GetEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KycServiceServer).GetEntity(ctx, req.(*GetEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KycService_GetEntityDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntityDocsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KycServiceServer).GetEntityDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KycService_GetEntityDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KycServiceServer).GetEntityDocuments(ctx, req.(*GetEntityDocsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KycService_SubmitKyc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitKycRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KycServiceServer).SubmitKyc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KycService_SubmitKyc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KycServiceServer).SubmitKyc(ctx, req.(*SubmitKycRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KycService_Metadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KycServiceServer).Metadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KycService_Metadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KycServiceServer).Metadata(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _KycService_Audit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KycServiceServer).Audit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KycService_Audit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KycServiceServer).Audit(ctx, req.(*GetEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KycService_ServiceDesc is the grpc.ServiceDesc for KycService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KycService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accesspoint.v1.KycService",
	HandlerType: (*KycServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListEntities",
			Handler:    _KycService_ListEntities_Handler,
		},
		{
			MethodName: "GetEntity",
			Handler:    _KycService_GetEntity_Handler,
		},
		{
			MethodName: "GetEntityDocuments",
			Handler:    _KycService_GetEntityDocuments_Handler,
		},
		{
			MethodName: "SubmitKyc",
			Handler:    _KycService_SubmitKyc_Handler,
		},
		{
			MethodName: "Metadata",
			Handler:    _KycService_Metadata_Handler,
		},
		{
			MethodName: "Audit",
			Handler:    _KycService_Audit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "access-point/kyc.proto",
}
