// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: switching-service/switching.proto

package switchingservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SwitchingService_RegisterBank_FullMethodName      = "/switchingservice.v1.SwitchingService/RegisterBank"
	SwitchingService_QueryBankBalance_FullMethodName  = "/switchingservice.v1.SwitchingService/QueryBankBalance"
	SwitchingService_QueryTokenBalance_FullMethodName = "/switchingservice.v1.SwitchingService/QueryTokenBalance"
	SwitchingService_HoldPayment_FullMethodName       = "/switchingservice.v1.SwitchingService/HoldPayment"
	SwitchingService_HoldBatchPayment_FullMethodName  = "/switchingservice.v1.SwitchingService/HoldBatchPayment"
	SwitchingService_CancelPayment_FullMethodName     = "/switchingservice.v1.SwitchingService/CancelPayment"
	SwitchingService_UnheldPayment_FullMethodName     = "/switchingservice.v1.SwitchingService/UnheldPayment"
	SwitchingService_ConfirmPayment_FullMethodName    = "/switchingservice.v1.SwitchingService/ConfirmPayment"
	SwitchingService_GetPaymentByUetr_FullMethodName  = "/switchingservice.v1.SwitchingService/GetPaymentByUetr"
	SwitchingService_DepositBank_FullMethodName       = "/switchingservice.v1.SwitchingService/DepositBank"
	SwitchingService_WithdrawBank_FullMethodName      = "/switchingservice.v1.SwitchingService/WithdrawBank"
	SwitchingService_MintToBankCode_FullMethodName    = "/switchingservice.v1.SwitchingService/MintToBankCode"
)

// SwitchingServiceClient is the client API for SwitchingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SwitchingService exposes the core operations that interact with the
// InterbankSettlementData and InterbankSettlementLogic smart contracts.
type SwitchingServiceClient interface {
	// Register a new bank into the settlement data contract.
	RegisterBank(ctx context.Context, in *RegisterBankRequest, opts ...grpc.CallOption) (*RegisterBankResponse, error)
	// Query the balance in smart contract (settlement data contract balance) of a bank by address.
	QueryBankBalance(ctx context.Context, in *QueryBalanceRequest, opts ...grpc.CallOption) (*QueryBalanceResponse, error)
	// Query the ERC20 token balance of a bank by address.
	QueryTokenBalance(ctx context.Context, in *QueryBalanceRequest, opts ...grpc.CallOption) (*QueryBalanceResponse, error)
	// Create a single hold payment request.
	HoldPayment(ctx context.Context, in *HoldPaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error)
	// Create a batch of hold payments in a single transaction.
	HoldBatchPayment(ctx context.Context, in *HoldBatchPaymentRequest, opts ...grpc.CallOption) (*BatchPaymentResponse, error)
	// Cancel a previously created hold payment (refund to sender) - for timeout/unhold.
	CancelPayment(ctx context.Context, in *CancelPaymentRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
	// Unhold a held payment manually (only receiver bank or operator can cancel).
	UnheldPayment(ctx context.Context, in *UnheldPaymentRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
	// Confirm a held payment and trigger settlement on-chain.
	ConfirmPayment(ctx context.Context, in *ConfirmPaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error)
	// Get payment status by UETR (offchain tracking reference).
	// Returns full on-chain hold payment information.
	GetPaymentByUetr(ctx context.Context, in *GetPaymentByUetrRequest, opts ...grpc.CallOption) (*PaymentInfo, error)
	// Deposit settlement tokens for a bank.
	DepositBank(ctx context.Context, in *BankTransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
	// Withdraw settlement tokens for a bank.
	WithdrawBank(ctx context.Context, in *BankTransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
	// Mint settlement tokens directly to a bank by its bank code.
	MintToBankCode(ctx context.Context, in *BankTransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
}

type switchingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSwitchingServiceClient(cc grpc.ClientConnInterface) SwitchingServiceClient {
	return &switchingServiceClient{cc}
}

func (c *switchingServiceClient) RegisterBank(ctx context.Context, in *RegisterBankRequest, opts ...grpc.CallOption) (*RegisterBankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterBankResponse)
	err := c.cc.Invoke(ctx, SwitchingService_RegisterBank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchingServiceClient) QueryBankBalance(ctx context.Context, in *QueryBalanceRequest, opts ...grpc.CallOption) (*QueryBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryBalanceResponse)
	err := c.cc.Invoke(ctx, SwitchingService_QueryBankBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchingServiceClient) QueryTokenBalance(ctx context.Context, in *QueryBalanceRequest, opts ...grpc.CallOption) (*QueryBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryBalanceResponse)
	err := c.cc.Invoke(ctx, SwitchingService_QueryTokenBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchingServiceClient) HoldPayment(ctx context.Context, in *HoldPaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentResponse)
	err := c.cc.Invoke(ctx, SwitchingService_HoldPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchingServiceClient) HoldBatchPayment(ctx context.Context, in *HoldBatchPaymentRequest, opts ...grpc.CallOption) (*BatchPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchPaymentResponse)
	err := c.cc.Invoke(ctx, SwitchingService_HoldBatchPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchingServiceClient) CancelPayment(ctx context.Context, in *CancelPaymentRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, SwitchingService_CancelPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchingServiceClient) UnheldPayment(ctx context.Context, in *UnheldPaymentRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, SwitchingService_UnheldPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchingServiceClient) ConfirmPayment(ctx context.Context, in *ConfirmPaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentResponse)
	err := c.cc.Invoke(ctx, SwitchingService_ConfirmPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchingServiceClient) GetPaymentByUetr(ctx context.Context, in *GetPaymentByUetrRequest, opts ...grpc.CallOption) (*PaymentInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentInfo)
	err := c.cc.Invoke(ctx, SwitchingService_GetPaymentByUetr_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchingServiceClient) DepositBank(ctx context.Context, in *BankTransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, SwitchingService_DepositBank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchingServiceClient) WithdrawBank(ctx context.Context, in *BankTransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, SwitchingService_WithdrawBank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchingServiceClient) MintToBankCode(ctx context.Context, in *BankTransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, SwitchingService_MintToBankCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SwitchingServiceServer is the server API for SwitchingService service.
// All implementations must embed UnimplementedSwitchingServiceServer
// for forward compatibility.
//
// SwitchingService exposes the core operations that interact with the
// InterbankSettlementData and InterbankSettlementLogic smart contracts.
type SwitchingServiceServer interface {
	// Register a new bank into the settlement data contract.
	RegisterBank(context.Context, *RegisterBankRequest) (*RegisterBankResponse, error)
	// Query the balance in smart contract (settlement data contract balance) of a bank by address.
	QueryBankBalance(context.Context, *QueryBalanceRequest) (*QueryBalanceResponse, error)
	// Query the ERC20 token balance of a bank by address.
	QueryTokenBalance(context.Context, *QueryBalanceRequest) (*QueryBalanceResponse, error)
	// Create a single hold payment request.
	HoldPayment(context.Context, *HoldPaymentRequest) (*PaymentResponse, error)
	// Create a batch of hold payments in a single transaction.
	HoldBatchPayment(context.Context, *HoldBatchPaymentRequest) (*BatchPaymentResponse, error)
	// Cancel a previously created hold payment (refund to sender) - for timeout/unhold.
	CancelPayment(context.Context, *CancelPaymentRequest) (*TransactionResponse, error)
	// Unhold a held payment manually (only receiver bank or operator can cancel).
	UnheldPayment(context.Context, *UnheldPaymentRequest) (*TransactionResponse, error)
	// Confirm a held payment and trigger settlement on-chain.
	ConfirmPayment(context.Context, *ConfirmPaymentRequest) (*PaymentResponse, error)
	// Get payment status by UETR (offchain tracking reference).
	// Returns full on-chain hold payment information.
	GetPaymentByUetr(context.Context, *GetPaymentByUetrRequest) (*PaymentInfo, error)
	// Deposit settlement tokens for a bank.
	DepositBank(context.Context, *BankTransactionRequest) (*TransactionResponse, error)
	// Withdraw settlement tokens for a bank.
	WithdrawBank(context.Context, *BankTransactionRequest) (*TransactionResponse, error)
	// Mint settlement tokens directly to a bank by its bank code.
	MintToBankCode(context.Context, *BankTransactionRequest) (*TransactionResponse, error)
	mustEmbedUnimplementedSwitchingServiceServer()
}

// UnimplementedSwitchingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSwitchingServiceServer struct{}

func (UnimplementedSwitchingServiceServer) RegisterBank(context.Context, *RegisterBankRequest) (*RegisterBankResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterBank not implemented")
}
func (UnimplementedSwitchingServiceServer) QueryBankBalance(context.Context, *QueryBalanceRequest) (*QueryBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryBankBalance not implemented")
}
func (UnimplementedSwitchingServiceServer) QueryTokenBalance(context.Context, *QueryBalanceRequest) (*QueryBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryTokenBalance not implemented")
}
func (UnimplementedSwitchingServiceServer) HoldPayment(context.Context, *HoldPaymentRequest) (*PaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HoldPayment not implemented")
}
func (UnimplementedSwitchingServiceServer) HoldBatchPayment(context.Context, *HoldBatchPaymentRequest) (*BatchPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HoldBatchPayment not implemented")
}
func (UnimplementedSwitchingServiceServer) CancelPayment(context.Context, *CancelPaymentRequest) (*TransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelPayment not implemented")
}
func (UnimplementedSwitchingServiceServer) UnheldPayment(context.Context, *UnheldPaymentRequest) (*TransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnheldPayment not implemented")
}
func (UnimplementedSwitchingServiceServer) ConfirmPayment(context.Context, *ConfirmPaymentRequest) (*PaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmPayment not implemented")
}
func (UnimplementedSwitchingServiceServer) GetPaymentByUetr(context.Context, *GetPaymentByUetrRequest) (*PaymentInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaymentByUetr not implemented")
}
func (UnimplementedSwitchingServiceServer) DepositBank(context.Context, *BankTransactionRequest) (*TransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DepositBank not implemented")
}
func (UnimplementedSwitchingServiceServer) WithdrawBank(context.Context, *BankTransactionRequest) (*TransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawBank not implemented")
}
func (UnimplementedSwitchingServiceServer) MintToBankCode(context.Context, *BankTransactionRequest) (*TransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MintToBankCode not implemented")
}
func (UnimplementedSwitchingServiceServer) mustEmbedUnimplementedSwitchingServiceServer() {}
func (UnimplementedSwitchingServiceServer) testEmbeddedByValue()                          {}

// UnsafeSwitchingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SwitchingServiceServer will
// result in compilation errors.
type UnsafeSwitchingServiceServer interface {
	mustEmbedUnimplementedSwitchingServiceServer()
}

func RegisterSwitchingServiceServer(s grpc.ServiceRegistrar, srv SwitchingServiceServer) {
	// If the following call pancis, it indicates UnimplementedSwitchingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SwitchingService_ServiceDesc, srv)
}

func _SwitchingService_RegisterBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterBankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchingServiceServer).RegisterBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchingService_RegisterBank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchingServiceServer).RegisterBank(ctx, req.(*RegisterBankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchingService_QueryBankBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchingServiceServer).QueryBankBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchingService_QueryBankBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchingServiceServer).QueryBankBalance(ctx, req.(*QueryBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchingService_QueryTokenBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchingServiceServer).QueryTokenBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchingService_QueryTokenBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchingServiceServer).QueryTokenBalance(ctx, req.(*QueryBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchingService_HoldPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HoldPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchingServiceServer).HoldPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchingService_HoldPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchingServiceServer).HoldPayment(ctx, req.(*HoldPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchingService_HoldBatchPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HoldBatchPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchingServiceServer).HoldBatchPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchingService_HoldBatchPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchingServiceServer).HoldBatchPayment(ctx, req.(*HoldBatchPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchingService_CancelPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchingServiceServer).CancelPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchingService_CancelPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchingServiceServer).CancelPayment(ctx, req.(*CancelPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchingService_UnheldPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnheldPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchingServiceServer).UnheldPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchingService_UnheldPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchingServiceServer).UnheldPayment(ctx, req.(*UnheldPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchingService_ConfirmPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchingServiceServer).ConfirmPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchingService_ConfirmPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchingServiceServer).ConfirmPayment(ctx, req.(*ConfirmPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchingService_GetPaymentByUetr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentByUetrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchingServiceServer).GetPaymentByUetr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchingService_GetPaymentByUetr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchingServiceServer).GetPaymentByUetr(ctx, req.(*GetPaymentByUetrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchingService_DepositBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BankTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchingServiceServer).DepositBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchingService_DepositBank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchingServiceServer).DepositBank(ctx, req.(*BankTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchingService_WithdrawBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BankTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchingServiceServer).WithdrawBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchingService_WithdrawBank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchingServiceServer).WithdrawBank(ctx, req.(*BankTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchingService_MintToBankCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BankTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchingServiceServer).MintToBankCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchingService_MintToBankCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchingServiceServer).MintToBankCode(ctx, req.(*BankTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SwitchingService_ServiceDesc is the grpc.ServiceDesc for SwitchingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SwitchingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "switchingservice.v1.SwitchingService",
	HandlerType: (*SwitchingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterBank",
			Handler:    _SwitchingService_RegisterBank_Handler,
		},
		{
			MethodName: "QueryBankBalance",
			Handler:    _SwitchingService_QueryBankBalance_Handler,
		},
		{
			MethodName: "QueryTokenBalance",
			Handler:    _SwitchingService_QueryTokenBalance_Handler,
		},
		{
			MethodName: "HoldPayment",
			Handler:    _SwitchingService_HoldPayment_Handler,
		},
		{
			MethodName: "HoldBatchPayment",
			Handler:    _SwitchingService_HoldBatchPayment_Handler,
		},
		{
			MethodName: "CancelPayment",
			Handler:    _SwitchingService_CancelPayment_Handler,
		},
		{
			MethodName: "UnheldPayment",
			Handler:    _SwitchingService_UnheldPayment_Handler,
		},
		{
			MethodName: "ConfirmPayment",
			Handler:    _SwitchingService_ConfirmPayment_Handler,
		},
		{
			MethodName: "GetPaymentByUetr",
			Handler:    _SwitchingService_GetPaymentByUetr_Handler,
		},
		{
			MethodName: "DepositBank",
			Handler:    _SwitchingService_DepositBank_Handler,
		},
		{
			MethodName: "WithdrawBank",
			Handler:    _SwitchingService_WithdrawBank_Handler,
		},
		{
			MethodName: "MintToBankCode",
			Handler:    _SwitchingService_MintToBankCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "switching-service/switching.proto",
}
