// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification/error.proto

package com.blcvn.switching.notification;

public final class Error {
  private Error() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * ResultCode định nghĩa các mã kết quả được sử dụng trong hệ thống notification
   * </pre>
   *
   * Protobuf enum {@code notification.v1.ResultCode}
   */
  public enum ResultCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Giá trị mặc định, không xác định
     * </pre>
     *
     * <code>UNSPECIFIED = 0;</code>
     */
    UNSPECIFIED(0),
    /**
     * <pre>
     * Thành công
     * </pre>
     *
     * <code>SUCCESS = 200;</code>
     */
    SUCCESS(200),
    /**
     * <pre>
     * Lỗi validation hoặc request không hợp lệ
     * </pre>
     *
     * <code>BAD_REQUEST = 400;</code>
     */
    BAD_REQUEST(400),
    /**
     * <pre>
     * Chưa xác thực hoặc token không hợp lệ
     * </pre>
     *
     * <code>UNAUTHORIZED = 401;</code>
     */
    UNAUTHORIZED(401),
    /**
     * <pre>
     * Không có quyền truy cập
     * </pre>
     *
     * <code>FORBIDDEN = 403;</code>
     */
    FORBIDDEN(403),
    /**
     * <pre>
     * Không tìm thấy tài nguyên
     * </pre>
     *
     * <code>NOT_FOUND = 404;</code>
     */
    NOT_FOUND(404),
    /**
     * <pre>
     * Request trùng lặp
     * </pre>
     *
     * <code>DUPLICATE_REQUEST = 409;</code>
     */
    DUPLICATE_REQUEST(409),
    /**
     * <pre>
     * Dữ liệu không thể xử lý
     * </pre>
     *
     * <code>UNPROCESSABLE_ENTITY = 422;</code>
     */
    UNPROCESSABLE_ENTITY(422),
    /**
     * <pre>
     * Quá nhiều request trong khoảng thời gian
     * </pre>
     *
     * <code>TOO_MANY_REQUESTS = 429;</code>
     */
    TOO_MANY_REQUESTS(429),
    /**
     * <pre>
     * Lỗi nội bộ của server
     * </pre>
     *
     * <code>INTERNAL = 500;</code>
     */
    INTERNAL(500),
    /**
     * <pre>
     * Lỗi gateway
     * </pre>
     *
     * <code>BAD_GATEWAY = 502;</code>
     */
    BAD_GATEWAY(502),
    /**
     * <pre>
     * Dịch vụ không khả dụng
     * </pre>
     *
     * <code>SERVICE_UNAVAILABLE = 503;</code>
     */
    SERVICE_UNAVAILABLE(503),
    /**
     * <pre>
     * Gateway timeout
     * </pre>
     *
     * <code>GATEWAY_TIMEOUT = 504;</code>
     */
    GATEWAY_TIMEOUT(504),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * Giá trị mặc định, không xác định
     * </pre>
     *
     * <code>UNSPECIFIED = 0;</code>
     */
    public static final int UNSPECIFIED_VALUE = 0;
    /**
     * <pre>
     * Thành công
     * </pre>
     *
     * <code>SUCCESS = 200;</code>
     */
    public static final int SUCCESS_VALUE = 200;
    /**
     * <pre>
     * Lỗi validation hoặc request không hợp lệ
     * </pre>
     *
     * <code>BAD_REQUEST = 400;</code>
     */
    public static final int BAD_REQUEST_VALUE = 400;
    /**
     * <pre>
     * Chưa xác thực hoặc token không hợp lệ
     * </pre>
     *
     * <code>UNAUTHORIZED = 401;</code>
     */
    public static final int UNAUTHORIZED_VALUE = 401;
    /**
     * <pre>
     * Không có quyền truy cập
     * </pre>
     *
     * <code>FORBIDDEN = 403;</code>
     */
    public static final int FORBIDDEN_VALUE = 403;
    /**
     * <pre>
     * Không tìm thấy tài nguyên
     * </pre>
     *
     * <code>NOT_FOUND = 404;</code>
     */
    public static final int NOT_FOUND_VALUE = 404;
    /**
     * <pre>
     * Request trùng lặp
     * </pre>
     *
     * <code>DUPLICATE_REQUEST = 409;</code>
     */
    public static final int DUPLICATE_REQUEST_VALUE = 409;
    /**
     * <pre>
     * Dữ liệu không thể xử lý
     * </pre>
     *
     * <code>UNPROCESSABLE_ENTITY = 422;</code>
     */
    public static final int UNPROCESSABLE_ENTITY_VALUE = 422;
    /**
     * <pre>
     * Quá nhiều request trong khoảng thời gian
     * </pre>
     *
     * <code>TOO_MANY_REQUESTS = 429;</code>
     */
    public static final int TOO_MANY_REQUESTS_VALUE = 429;
    /**
     * <pre>
     * Lỗi nội bộ của server
     * </pre>
     *
     * <code>INTERNAL = 500;</code>
     */
    public static final int INTERNAL_VALUE = 500;
    /**
     * <pre>
     * Lỗi gateway
     * </pre>
     *
     * <code>BAD_GATEWAY = 502;</code>
     */
    public static final int BAD_GATEWAY_VALUE = 502;
    /**
     * <pre>
     * Dịch vụ không khả dụng
     * </pre>
     *
     * <code>SERVICE_UNAVAILABLE = 503;</code>
     */
    public static final int SERVICE_UNAVAILABLE_VALUE = 503;
    /**
     * <pre>
     * Gateway timeout
     * </pre>
     *
     * <code>GATEWAY_TIMEOUT = 504;</code>
     */
    public static final int GATEWAY_TIMEOUT_VALUE = 504;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResultCode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ResultCode forNumber(int value) {
      switch (value) {
        case 0: return UNSPECIFIED;
        case 200: return SUCCESS;
        case 400: return BAD_REQUEST;
        case 401: return UNAUTHORIZED;
        case 403: return FORBIDDEN;
        case 404: return NOT_FOUND;
        case 409: return DUPLICATE_REQUEST;
        case 422: return UNPROCESSABLE_ENTITY;
        case 429: return TOO_MANY_REQUESTS;
        case 500: return INTERNAL;
        case 502: return BAD_GATEWAY;
        case 503: return SERVICE_UNAVAILABLE;
        case 504: return GATEWAY_TIMEOUT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResultCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ResultCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResultCode>() {
            public ResultCode findValueByNumber(int number) {
              return ResultCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.blcvn.switching.notification.Error.getDescriptor().getEnumTypes().get(0);
    }

    private static final ResultCode[] VALUES = values();

    public static ResultCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ResultCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:notification.v1.ResultCode)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030notification/error.proto\022\017notification" +
      ".v1*\214\002\n\nResultCode\022\017\n\013UNSPECIFIED\020\000\022\014\n\007S" +
      "UCCESS\020\310\001\022\020\n\013BAD_REQUEST\020\220\003\022\021\n\014UNAUTHORI" +
      "ZED\020\221\003\022\016\n\tFORBIDDEN\020\223\003\022\016\n\tNOT_FOUND\020\224\003\022\026" +
      "\n\021DUPLICATE_REQUEST\020\231\003\022\031\n\024UNPROCESSABLE_" +
      "ENTITY\020\246\003\022\026\n\021TOO_MANY_REQUESTS\020\255\003\022\r\n\010INT" +
      "ERNAL\020\364\003\022\020\n\013BAD_GATEWAY\020\366\003\022\030\n\023SERVICE_UN" +
      "AVAILABLE\020\367\003\022\024\n\017GATEWAY_TIMEOUT\020\370\003Ba\n co" +
      "m.blcvn.switching.notificationZ=github.c" +
      "om/blcvn/switching-proto/go/notification" +
      ";notificationb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
