// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: offchain/auth.proto

package com.blcvn.switching.offchain;

public final class Auth {
  private Auth() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TokenRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:offchain.v1.TokenRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string grant_type = 1;</code>
     * @return The grantType.
     */
    java.lang.String getGrantType();
    /**
     * <code>string grant_type = 1;</code>
     * @return The bytes for grantType.
     */
    com.google.protobuf.ByteString
        getGrantTypeBytes();

    /**
     * <code>string client_id = 2;</code>
     * @return The clientId.
     */
    java.lang.String getClientId();
    /**
     * <code>string client_id = 2;</code>
     * @return The bytes for clientId.
     */
    com.google.protobuf.ByteString
        getClientIdBytes();

    /**
     * <code>string client_secret = 3;</code>
     * @return The clientSecret.
     */
    java.lang.String getClientSecret();
    /**
     * <code>string client_secret = 3;</code>
     * @return The bytes for clientSecret.
     */
    com.google.protobuf.ByteString
        getClientSecretBytes();
  }
  /**
   * Protobuf type {@code offchain.v1.TokenRequest}
   */
  public static final class TokenRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:offchain.v1.TokenRequest)
      TokenRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TokenRequest.newBuilder() to construct.
    private TokenRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TokenRequest() {
      grantType_ = "";
      clientId_ = "";
      clientSecret_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TokenRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TokenRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              grantType_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              clientId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              clientSecret_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blcvn.switching.offchain.Auth.internal_static_offchain_v1_TokenRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blcvn.switching.offchain.Auth.internal_static_offchain_v1_TokenRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blcvn.switching.offchain.Auth.TokenRequest.class, com.blcvn.switching.offchain.Auth.TokenRequest.Builder.class);
    }

    public static final int GRANT_TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object grantType_;
    /**
     * <code>string grant_type = 1;</code>
     * @return The grantType.
     */
    @java.lang.Override
    public java.lang.String getGrantType() {
      java.lang.Object ref = grantType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        grantType_ = s;
        return s;
      }
    }
    /**
     * <code>string grant_type = 1;</code>
     * @return The bytes for grantType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGrantTypeBytes() {
      java.lang.Object ref = grantType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        grantType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENT_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object clientId_;
    /**
     * <code>string client_id = 2;</code>
     * @return The clientId.
     */
    @java.lang.Override
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      }
    }
    /**
     * <code>string client_id = 2;</code>
     * @return The bytes for clientId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENT_SECRET_FIELD_NUMBER = 3;
    private volatile java.lang.Object clientSecret_;
    /**
     * <code>string client_secret = 3;</code>
     * @return The clientSecret.
     */
    @java.lang.Override
    public java.lang.String getClientSecret() {
      java.lang.Object ref = clientSecret_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientSecret_ = s;
        return s;
      }
    }
    /**
     * <code>string client_secret = 3;</code>
     * @return The bytes for clientSecret.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClientSecretBytes() {
      java.lang.Object ref = clientSecret_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientSecret_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getGrantTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, grantType_);
      }
      if (!getClientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clientId_);
      }
      if (!getClientSecretBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, clientSecret_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getGrantTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, grantType_);
      }
      if (!getClientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clientId_);
      }
      if (!getClientSecretBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, clientSecret_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.blcvn.switching.offchain.Auth.TokenRequest)) {
        return super.equals(obj);
      }
      com.blcvn.switching.offchain.Auth.TokenRequest other = (com.blcvn.switching.offchain.Auth.TokenRequest) obj;

      if (!getGrantType()
          .equals(other.getGrantType())) return false;
      if (!getClientId()
          .equals(other.getClientId())) return false;
      if (!getClientSecret()
          .equals(other.getClientSecret())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GRANT_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getGrantType().hashCode();
      hash = (37 * hash) + CLIENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getClientId().hashCode();
      hash = (37 * hash) + CLIENT_SECRET_FIELD_NUMBER;
      hash = (53 * hash) + getClientSecret().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.blcvn.switching.offchain.Auth.TokenRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blcvn.switching.offchain.Auth.TokenRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blcvn.switching.offchain.Auth.TokenRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blcvn.switching.offchain.Auth.TokenRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blcvn.switching.offchain.Auth.TokenRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blcvn.switching.offchain.Auth.TokenRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blcvn.switching.offchain.Auth.TokenRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.blcvn.switching.offchain.Auth.TokenRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.blcvn.switching.offchain.Auth.TokenRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.blcvn.switching.offchain.Auth.TokenRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.blcvn.switching.offchain.Auth.TokenRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.blcvn.switching.offchain.Auth.TokenRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.blcvn.switching.offchain.Auth.TokenRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code offchain.v1.TokenRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:offchain.v1.TokenRequest)
        com.blcvn.switching.offchain.Auth.TokenRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.blcvn.switching.offchain.Auth.internal_static_offchain_v1_TokenRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.blcvn.switching.offchain.Auth.internal_static_offchain_v1_TokenRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.blcvn.switching.offchain.Auth.TokenRequest.class, com.blcvn.switching.offchain.Auth.TokenRequest.Builder.class);
      }

      // Construct using com.blcvn.switching.offchain.Auth.TokenRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        grantType_ = "";

        clientId_ = "";

        clientSecret_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.blcvn.switching.offchain.Auth.internal_static_offchain_v1_TokenRequest_descriptor;
      }

      @java.lang.Override
      public com.blcvn.switching.offchain.Auth.TokenRequest getDefaultInstanceForType() {
        return com.blcvn.switching.offchain.Auth.TokenRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.blcvn.switching.offchain.Auth.TokenRequest build() {
        com.blcvn.switching.offchain.Auth.TokenRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.blcvn.switching.offchain.Auth.TokenRequest buildPartial() {
        com.blcvn.switching.offchain.Auth.TokenRequest result = new com.blcvn.switching.offchain.Auth.TokenRequest(this);
        result.grantType_ = grantType_;
        result.clientId_ = clientId_;
        result.clientSecret_ = clientSecret_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.blcvn.switching.offchain.Auth.TokenRequest) {
          return mergeFrom((com.blcvn.switching.offchain.Auth.TokenRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.blcvn.switching.offchain.Auth.TokenRequest other) {
        if (other == com.blcvn.switching.offchain.Auth.TokenRequest.getDefaultInstance()) return this;
        if (!other.getGrantType().isEmpty()) {
          grantType_ = other.grantType_;
          onChanged();
        }
        if (!other.getClientId().isEmpty()) {
          clientId_ = other.clientId_;
          onChanged();
        }
        if (!other.getClientSecret().isEmpty()) {
          clientSecret_ = other.clientSecret_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.blcvn.switching.offchain.Auth.TokenRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.blcvn.switching.offchain.Auth.TokenRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object grantType_ = "";
      /**
       * <code>string grant_type = 1;</code>
       * @return The grantType.
       */
      public java.lang.String getGrantType() {
        java.lang.Object ref = grantType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          grantType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string grant_type = 1;</code>
       * @return The bytes for grantType.
       */
      public com.google.protobuf.ByteString
          getGrantTypeBytes() {
        java.lang.Object ref = grantType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          grantType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string grant_type = 1;</code>
       * @param value The grantType to set.
       * @return This builder for chaining.
       */
      public Builder setGrantType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        grantType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string grant_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearGrantType() {
        
        grantType_ = getDefaultInstance().getGrantType();
        onChanged();
        return this;
      }
      /**
       * <code>string grant_type = 1;</code>
       * @param value The bytes for grantType to set.
       * @return This builder for chaining.
       */
      public Builder setGrantTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        grantType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clientId_ = "";
      /**
       * <code>string client_id = 2;</code>
       * @return The clientId.
       */
      public java.lang.String getClientId() {
        java.lang.Object ref = clientId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string client_id = 2;</code>
       * @return The bytes for clientId.
       */
      public com.google.protobuf.ByteString
          getClientIdBytes() {
        java.lang.Object ref = clientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string client_id = 2;</code>
       * @param value The clientId to set.
       * @return This builder for chaining.
       */
      public Builder setClientId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string client_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientId() {
        
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }
      /**
       * <code>string client_id = 2;</code>
       * @param value The bytes for clientId to set.
       * @return This builder for chaining.
       */
      public Builder setClientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clientSecret_ = "";
      /**
       * <code>string client_secret = 3;</code>
       * @return The clientSecret.
       */
      public java.lang.String getClientSecret() {
        java.lang.Object ref = clientSecret_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientSecret_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string client_secret = 3;</code>
       * @return The bytes for clientSecret.
       */
      public com.google.protobuf.ByteString
          getClientSecretBytes() {
        java.lang.Object ref = clientSecret_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientSecret_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string client_secret = 3;</code>
       * @param value The clientSecret to set.
       * @return This builder for chaining.
       */
      public Builder setClientSecret(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientSecret_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string client_secret = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientSecret() {
        
        clientSecret_ = getDefaultInstance().getClientSecret();
        onChanged();
        return this;
      }
      /**
       * <code>string client_secret = 3;</code>
       * @param value The bytes for clientSecret to set.
       * @return This builder for chaining.
       */
      public Builder setClientSecretBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientSecret_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:offchain.v1.TokenRequest)
    }

    // @@protoc_insertion_point(class_scope:offchain.v1.TokenRequest)
    private static final com.blcvn.switching.offchain.Auth.TokenRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.blcvn.switching.offchain.Auth.TokenRequest();
    }

    public static com.blcvn.switching.offchain.Auth.TokenRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TokenRequest>
        PARSER = new com.google.protobuf.AbstractParser<TokenRequest>() {
      @java.lang.Override
      public TokenRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TokenRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TokenRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TokenRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.blcvn.switching.offchain.Auth.TokenRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TokenResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:offchain.v1.TokenResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string access_token = 1;</code>
     * @return The accessToken.
     */
    java.lang.String getAccessToken();
    /**
     * <code>string access_token = 1;</code>
     * @return The bytes for accessToken.
     */
    com.google.protobuf.ByteString
        getAccessTokenBytes();

    /**
     * <code>string token_type = 2;</code>
     * @return The tokenType.
     */
    java.lang.String getTokenType();
    /**
     * <code>string token_type = 2;</code>
     * @return The bytes for tokenType.
     */
    com.google.protobuf.ByteString
        getTokenTypeBytes();

    /**
     * <code>int32 expires_in = 3;</code>
     * @return The expiresIn.
     */
    int getExpiresIn();
  }
  /**
   * Protobuf type {@code offchain.v1.TokenResponse}
   */
  public static final class TokenResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:offchain.v1.TokenResponse)
      TokenResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TokenResponse.newBuilder() to construct.
    private TokenResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TokenResponse() {
      accessToken_ = "";
      tokenType_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TokenResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TokenResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              accessToken_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              tokenType_ = s;
              break;
            }
            case 24: {

              expiresIn_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blcvn.switching.offchain.Auth.internal_static_offchain_v1_TokenResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blcvn.switching.offchain.Auth.internal_static_offchain_v1_TokenResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blcvn.switching.offchain.Auth.TokenResponse.class, com.blcvn.switching.offchain.Auth.TokenResponse.Builder.class);
    }

    public static final int ACCESS_TOKEN_FIELD_NUMBER = 1;
    private volatile java.lang.Object accessToken_;
    /**
     * <code>string access_token = 1;</code>
     * @return The accessToken.
     */
    @java.lang.Override
    public java.lang.String getAccessToken() {
      java.lang.Object ref = accessToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accessToken_ = s;
        return s;
      }
    }
    /**
     * <code>string access_token = 1;</code>
     * @return The bytes for accessToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccessTokenBytes() {
      java.lang.Object ref = accessToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accessToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_TYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object tokenType_;
    /**
     * <code>string token_type = 2;</code>
     * @return The tokenType.
     */
    @java.lang.Override
    public java.lang.String getTokenType() {
      java.lang.Object ref = tokenType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tokenType_ = s;
        return s;
      }
    }
    /**
     * <code>string token_type = 2;</code>
     * @return The bytes for tokenType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenTypeBytes() {
      java.lang.Object ref = tokenType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tokenType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXPIRES_IN_FIELD_NUMBER = 3;
    private int expiresIn_;
    /**
     * <code>int32 expires_in = 3;</code>
     * @return The expiresIn.
     */
    @java.lang.Override
    public int getExpiresIn() {
      return expiresIn_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAccessTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, accessToken_);
      }
      if (!getTokenTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tokenType_);
      }
      if (expiresIn_ != 0) {
        output.writeInt32(3, expiresIn_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAccessTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, accessToken_);
      }
      if (!getTokenTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tokenType_);
      }
      if (expiresIn_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, expiresIn_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.blcvn.switching.offchain.Auth.TokenResponse)) {
        return super.equals(obj);
      }
      com.blcvn.switching.offchain.Auth.TokenResponse other = (com.blcvn.switching.offchain.Auth.TokenResponse) obj;

      if (!getAccessToken()
          .equals(other.getAccessToken())) return false;
      if (!getTokenType()
          .equals(other.getTokenType())) return false;
      if (getExpiresIn()
          != other.getExpiresIn()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACCESS_TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getAccessToken().hashCode();
      hash = (37 * hash) + TOKEN_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getTokenType().hashCode();
      hash = (37 * hash) + EXPIRES_IN_FIELD_NUMBER;
      hash = (53 * hash) + getExpiresIn();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.blcvn.switching.offchain.Auth.TokenResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blcvn.switching.offchain.Auth.TokenResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blcvn.switching.offchain.Auth.TokenResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blcvn.switching.offchain.Auth.TokenResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blcvn.switching.offchain.Auth.TokenResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blcvn.switching.offchain.Auth.TokenResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blcvn.switching.offchain.Auth.TokenResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.blcvn.switching.offchain.Auth.TokenResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.blcvn.switching.offchain.Auth.TokenResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.blcvn.switching.offchain.Auth.TokenResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.blcvn.switching.offchain.Auth.TokenResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.blcvn.switching.offchain.Auth.TokenResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.blcvn.switching.offchain.Auth.TokenResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code offchain.v1.TokenResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:offchain.v1.TokenResponse)
        com.blcvn.switching.offchain.Auth.TokenResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.blcvn.switching.offchain.Auth.internal_static_offchain_v1_TokenResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.blcvn.switching.offchain.Auth.internal_static_offchain_v1_TokenResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.blcvn.switching.offchain.Auth.TokenResponse.class, com.blcvn.switching.offchain.Auth.TokenResponse.Builder.class);
      }

      // Construct using com.blcvn.switching.offchain.Auth.TokenResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        accessToken_ = "";

        tokenType_ = "";

        expiresIn_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.blcvn.switching.offchain.Auth.internal_static_offchain_v1_TokenResponse_descriptor;
      }

      @java.lang.Override
      public com.blcvn.switching.offchain.Auth.TokenResponse getDefaultInstanceForType() {
        return com.blcvn.switching.offchain.Auth.TokenResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.blcvn.switching.offchain.Auth.TokenResponse build() {
        com.blcvn.switching.offchain.Auth.TokenResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.blcvn.switching.offchain.Auth.TokenResponse buildPartial() {
        com.blcvn.switching.offchain.Auth.TokenResponse result = new com.blcvn.switching.offchain.Auth.TokenResponse(this);
        result.accessToken_ = accessToken_;
        result.tokenType_ = tokenType_;
        result.expiresIn_ = expiresIn_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.blcvn.switching.offchain.Auth.TokenResponse) {
          return mergeFrom((com.blcvn.switching.offchain.Auth.TokenResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.blcvn.switching.offchain.Auth.TokenResponse other) {
        if (other == com.blcvn.switching.offchain.Auth.TokenResponse.getDefaultInstance()) return this;
        if (!other.getAccessToken().isEmpty()) {
          accessToken_ = other.accessToken_;
          onChanged();
        }
        if (!other.getTokenType().isEmpty()) {
          tokenType_ = other.tokenType_;
          onChanged();
        }
        if (other.getExpiresIn() != 0) {
          setExpiresIn(other.getExpiresIn());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.blcvn.switching.offchain.Auth.TokenResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.blcvn.switching.offchain.Auth.TokenResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object accessToken_ = "";
      /**
       * <code>string access_token = 1;</code>
       * @return The accessToken.
       */
      public java.lang.String getAccessToken() {
        java.lang.Object ref = accessToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          accessToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string access_token = 1;</code>
       * @return The bytes for accessToken.
       */
      public com.google.protobuf.ByteString
          getAccessTokenBytes() {
        java.lang.Object ref = accessToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accessToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string access_token = 1;</code>
       * @param value The accessToken to set.
       * @return This builder for chaining.
       */
      public Builder setAccessToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        accessToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string access_token = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccessToken() {
        
        accessToken_ = getDefaultInstance().getAccessToken();
        onChanged();
        return this;
      }
      /**
       * <code>string access_token = 1;</code>
       * @param value The bytes for accessToken to set.
       * @return This builder for chaining.
       */
      public Builder setAccessTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        accessToken_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tokenType_ = "";
      /**
       * <code>string token_type = 2;</code>
       * @return The tokenType.
       */
      public java.lang.String getTokenType() {
        java.lang.Object ref = tokenType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tokenType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token_type = 2;</code>
       * @return The bytes for tokenType.
       */
      public com.google.protobuf.ByteString
          getTokenTypeBytes() {
        java.lang.Object ref = tokenType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tokenType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token_type = 2;</code>
       * @param value The tokenType to set.
       * @return This builder for chaining.
       */
      public Builder setTokenType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tokenType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token_type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTokenType() {
        
        tokenType_ = getDefaultInstance().getTokenType();
        onChanged();
        return this;
      }
      /**
       * <code>string token_type = 2;</code>
       * @param value The bytes for tokenType to set.
       * @return This builder for chaining.
       */
      public Builder setTokenTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tokenType_ = value;
        onChanged();
        return this;
      }

      private int expiresIn_ ;
      /**
       * <code>int32 expires_in = 3;</code>
       * @return The expiresIn.
       */
      @java.lang.Override
      public int getExpiresIn() {
        return expiresIn_;
      }
      /**
       * <code>int32 expires_in = 3;</code>
       * @param value The expiresIn to set.
       * @return This builder for chaining.
       */
      public Builder setExpiresIn(int value) {
        
        expiresIn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 expires_in = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearExpiresIn() {
        
        expiresIn_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:offchain.v1.TokenResponse)
    }

    // @@protoc_insertion_point(class_scope:offchain.v1.TokenResponse)
    private static final com.blcvn.switching.offchain.Auth.TokenResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.blcvn.switching.offchain.Auth.TokenResponse();
    }

    public static com.blcvn.switching.offchain.Auth.TokenResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TokenResponse>
        PARSER = new com.google.protobuf.AbstractParser<TokenResponse>() {
      @java.lang.Override
      public TokenResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TokenResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TokenResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TokenResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.blcvn.switching.offchain.Auth.TokenResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_offchain_v1_TokenRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_offchain_v1_TokenRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_offchain_v1_TokenResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_offchain_v1_TokenResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023offchain/auth.proto\022\013offchain.v1\"L\n\014To" +
      "kenRequest\022\022\n\ngrant_type\030\001 \001(\t\022\021\n\tclient" +
      "_id\030\002 \001(\t\022\025\n\rclient_secret\030\003 \001(\t\"M\n\rToke" +
      "nResponse\022\024\n\014access_token\030\001 \001(\t\022\022\n\ntoken" +
      "_type\030\002 \001(\t\022\022\n\nexpires_in\030\003 \001(\0052O\n\013AuthS" +
      "ervice\022@\n\005Token\022\031.offchain.v1.TokenReque" +
      "st\032\032.offchain.v1.TokenResponse\"\000BU\n\034com." +
      "blcvn.switching.offchainZ5github.com/blc" +
      "vn/switching-proto/go/offchain;offchainb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_offchain_v1_TokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_offchain_v1_TokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_offchain_v1_TokenRequest_descriptor,
        new java.lang.String[] { "GrantType", "ClientId", "ClientSecret", });
    internal_static_offchain_v1_TokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_offchain_v1_TokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_offchain_v1_TokenResponse_descriptor,
        new java.lang.String[] { "AccessToken", "TokenType", "ExpiresIn", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
