// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: offchain/gpi.proto

package offchain

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uetr          string                 `protobuf:"bytes,1,opt,name=uetr,proto3" json:"uetr,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	DebtorAgent   string                 `protobuf:"bytes,4,opt,name=debtor_agent,json=debtorAgent,proto3" json:"debtor_agent,omitempty"`
	CreditorAgent string                 `protobuf:"bytes,5,opt,name=creditor_agent,json=creditorAgent,proto3" json:"creditor_agent,omitempty"`
	EndToEndId    string                 `protobuf:"bytes,6,opt,name=end_to_end_id,json=endToEndId,proto3" json:"end_to_end_id,omitempty"`
	// Optional: structured account details for the sending bank's account (debtor)
	DebtorAgentAccount *Account `protobuf:"bytes,7,opt,name=debtor_agent_account,json=debtorAgentAccount,proto3" json:"debtor_agent_account,omitempty"`
	// Optional: structured account details for the receiving bank's account (creditor)
	CreditorAgentAccount *Account `protobuf:"bytes,8,opt,name=creditor_agent_account,json=creditorAgentAccount,proto3" json:"creditor_agent_account,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_offchain_gpi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offchain_gpi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_offchain_gpi_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentRequest) GetUetr() string {
	if x != nil {
		return x.Uetr
	}
	return ""
}

func (x *CreatePaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePaymentRequest) GetDebtorAgent() string {
	if x != nil {
		return x.DebtorAgent
	}
	return ""
}

func (x *CreatePaymentRequest) GetCreditorAgent() string {
	if x != nil {
		return x.CreditorAgent
	}
	return ""
}

func (x *CreatePaymentRequest) GetEndToEndId() string {
	if x != nil {
		return x.EndToEndId
	}
	return ""
}

func (x *CreatePaymentRequest) GetDebtorAgentAccount() *Account {
	if x != nil {
		return x.DebtorAgentAccount
	}
	return nil
}

func (x *CreatePaymentRequest) GetCreditorAgentAccount() *Account {
	if x != nil {
		return x.CreditorAgentAccount
	}
	return nil
}

type CreatePaymentResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Uetr                 string                 `protobuf:"bytes,2,opt,name=uetr,proto3" json:"uetr,omitempty"`
	TransactionReference string                 `protobuf:"bytes,3,opt,name=transaction_reference,json=transactionReference,proto3" json:"transaction_reference,omitempty"`
	Status               string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ProcessingTimestamp  *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=processing_timestamp,json=processingTimestamp,proto3" json:"processing_timestamp,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_offchain_gpi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offchain_gpi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_offchain_gpi_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreatePaymentResponse) GetUetr() string {
	if x != nil {
		return x.Uetr
	}
	return ""
}

func (x *CreatePaymentResponse) GetTransactionReference() string {
	if x != nil {
		return x.TransactionReference
	}
	return ""
}

func (x *CreatePaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreatePaymentResponse) GetProcessingTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.ProcessingTimestamp
	}
	return nil
}

type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_offchain_gpi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offchain_gpi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_offchain_gpi_proto_rawDescGZIP(), []int{2}
}

func (x *GetPaymentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPaymentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uetr          string                 `protobuf:"bytes,1,opt,name=uetr,proto3" json:"uetr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentStatusRequest) Reset() {
	*x = GetPaymentStatusRequest{}
	mi := &file_offchain_gpi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentStatusRequest) ProtoMessage() {}

func (x *GetPaymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offchain_gpi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_offchain_gpi_proto_rawDescGZIP(), []int{3}
}

func (x *GetPaymentStatusRequest) GetUetr() string {
	if x != nil {
		return x.Uetr
	}
	return ""
}

type PaymentStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uetr          string                 `protobuf:"bytes,1,opt,name=uetr,proto3" json:"uetr,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentStatus) Reset() {
	*x = PaymentStatus{}
	mi := &file_offchain_gpi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentStatus) ProtoMessage() {}

func (x *PaymentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_offchain_gpi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentStatus.ProtoReflect.Descriptor instead.
func (*PaymentStatus) Descriptor() ([]byte, []int) {
	return file_offchain_gpi_proto_rawDescGZIP(), []int{4}
}

func (x *PaymentStatus) GetUetr() string {
	if x != nil {
		return x.Uetr
	}
	return ""
}

func (x *PaymentStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentStatus) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentStatus) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type ConfirmPaymentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uetr             string                 `protobuf:"bytes,1,opt,name=uetr,proto3" json:"uetr,omitempty"`
	ConfirmationType string                 `protobuf:"bytes,2,opt,name=confirmation_type,json=confirmationType,proto3" json:"confirmation_type,omitempty"`
	Timestamp        string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfirmPaymentRequest) Reset() {
	*x = ConfirmPaymentRequest{}
	mi := &file_offchain_gpi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentRequest) ProtoMessage() {}

func (x *ConfirmPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offchain_gpi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentRequest.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentRequest) Descriptor() ([]byte, []int) {
	return file_offchain_gpi_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmPaymentRequest) GetUetr() string {
	if x != nil {
		return x.Uetr
	}
	return ""
}

func (x *ConfirmPaymentRequest) GetConfirmationType() string {
	if x != nil {
		return x.ConfirmationType
	}
	return ""
}

func (x *ConfirmPaymentRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type ConfirmPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uetr          string                 `protobuf:"bytes,1,opt,name=uetr,proto3" json:"uetr,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPaymentResponse) Reset() {
	*x = ConfirmPaymentResponse{}
	mi := &file_offchain_gpi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentResponse) ProtoMessage() {}

func (x *ConfirmPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offchain_gpi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentResponse.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentResponse) Descriptor() ([]byte, []int) {
	return file_offchain_gpi_proto_rawDescGZIP(), []int{6}
}

func (x *ConfirmPaymentResponse) GetUetr() string {
	if x != nil {
		return x.Uetr
	}
	return ""
}

func (x *ConfirmPaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_offchain_gpi_proto protoreflect.FileDescriptor

const file_offchain_gpi_proto_rawDesc = "" +
	"\n" +
	"\x12offchain/gpi.proto\x12\voffchain.v1\x1a\x15offchain/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdf\x02\n" +
	"\x14CreatePaymentRequest\x12\x12\n" +
	"\x04uetr\x18\x01 \x01(\tR\x04uetr\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12!\n" +
	"\fdebtor_agent\x18\x04 \x01(\tR\vdebtorAgent\x12%\n" +
	"\x0ecreditor_agent\x18\x05 \x01(\tR\rcreditorAgent\x12!\n" +
	"\rend_to_end_id\x18\x06 \x01(\tR\n" +
	"endToEndId\x12F\n" +
	"\x14debtor_agent_account\x18\a \x01(\v2\x14.offchain.v1.AccountR\x12debtorAgentAccount\x12J\n" +
	"\x16creditor_agent_account\x18\b \x01(\v2\x14.offchain.v1.AccountR\x14creditorAgentAccount\"\xd7\x01\n" +
	"\x15CreatePaymentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04uetr\x18\x02 \x01(\tR\x04uetr\x123\n" +
	"\x15transaction_reference\x18\x03 \x01(\tR\x14transactionReference\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12M\n" +
	"\x14processing_timestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x13processingTimestamp\"#\n" +
	"\x11GetPaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"-\n" +
	"\x17GetPaymentStatusRequest\x12\x12\n" +
	"\x04uetr\x18\x01 \x01(\tR\x04uetr\"o\n" +
	"\rPaymentStatus\x12\x12\n" +
	"\x04uetr\x18\x01 \x01(\tR\x04uetr\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"v\n" +
	"\x15ConfirmPaymentRequest\x12\x12\n" +
	"\x04uetr\x18\x01 \x01(\tR\x04uetr\x12+\n" +
	"\x11confirmation_type\x18\x02 \x01(\tR\x10confirmationType\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"D\n" +
	"\x16ConfirmPaymentResponse\x12\x12\n" +
	"\x04uetr\x18\x01 \x01(\tR\x04uetr\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xe1\x02\n" +
	"\n" +
	"GpiService\x12X\n" +
	"\rCreatePayment\x12!.offchain.v1.CreatePaymentRequest\x1a\".offchain.v1.CreatePaymentResponse\"\x00\x12D\n" +
	"\n" +
	"GetPayment\x12\x1e.offchain.v1.GetPaymentRequest\x1a\x14.offchain.v1.Payment\"\x00\x12V\n" +
	"\x10GetPaymentStatus\x12$.offchain.v1.GetPaymentStatusRequest\x1a\x1a.offchain.v1.PaymentStatus\"\x00\x12[\n" +
	"\x0eConfirmPayment\x12\".offchain.v1.ConfirmPaymentRequest\x1a#.offchain.v1.ConfirmPaymentResponse\"\x00BU\n" +
	"\x1ccom.blcvn.switching.offchainZ5github.com/blcvn/switching-proto/go/offchain;offchainb\x06proto3"

var (
	file_offchain_gpi_proto_rawDescOnce sync.Once
	file_offchain_gpi_proto_rawDescData []byte
)

func file_offchain_gpi_proto_rawDescGZIP() []byte {
	file_offchain_gpi_proto_rawDescOnce.Do(func() {
		file_offchain_gpi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_offchain_gpi_proto_rawDesc), len(file_offchain_gpi_proto_rawDesc)))
	})
	return file_offchain_gpi_proto_rawDescData
}

var file_offchain_gpi_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_offchain_gpi_proto_goTypes = []any{
	(*CreatePaymentRequest)(nil),    // 0: offchain.v1.CreatePaymentRequest
	(*CreatePaymentResponse)(nil),   // 1: offchain.v1.CreatePaymentResponse
	(*GetPaymentRequest)(nil),       // 2: offchain.v1.GetPaymentRequest
	(*GetPaymentStatusRequest)(nil), // 3: offchain.v1.GetPaymentStatusRequest
	(*PaymentStatus)(nil),           // 4: offchain.v1.PaymentStatus
	(*ConfirmPaymentRequest)(nil),   // 5: offchain.v1.ConfirmPaymentRequest
	(*ConfirmPaymentResponse)(nil),  // 6: offchain.v1.ConfirmPaymentResponse
	(*Account)(nil),                 // 7: offchain.v1.Account
	(*timestamp.Timestamp)(nil),     // 8: google.protobuf.Timestamp
	(*Payment)(nil),                 // 9: offchain.v1.Payment
}
var file_offchain_gpi_proto_depIdxs = []int32{
	7, // 0: offchain.v1.CreatePaymentRequest.debtor_agent_account:type_name -> offchain.v1.Account
	7, // 1: offchain.v1.CreatePaymentRequest.creditor_agent_account:type_name -> offchain.v1.Account
	8, // 2: offchain.v1.CreatePaymentResponse.processing_timestamp:type_name -> google.protobuf.Timestamp
	0, // 3: offchain.v1.GpiService.CreatePayment:input_type -> offchain.v1.CreatePaymentRequest
	2, // 4: offchain.v1.GpiService.GetPayment:input_type -> offchain.v1.GetPaymentRequest
	3, // 5: offchain.v1.GpiService.GetPaymentStatus:input_type -> offchain.v1.GetPaymentStatusRequest
	5, // 6: offchain.v1.GpiService.ConfirmPayment:input_type -> offchain.v1.ConfirmPaymentRequest
	1, // 7: offchain.v1.GpiService.CreatePayment:output_type -> offchain.v1.CreatePaymentResponse
	9, // 8: offchain.v1.GpiService.GetPayment:output_type -> offchain.v1.Payment
	4, // 9: offchain.v1.GpiService.GetPaymentStatus:output_type -> offchain.v1.PaymentStatus
	6, // 10: offchain.v1.GpiService.ConfirmPayment:output_type -> offchain.v1.ConfirmPaymentResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_offchain_gpi_proto_init() }
func file_offchain_gpi_proto_init() {
	if File_offchain_gpi_proto != nil {
		return
	}
	file_offchain_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_offchain_gpi_proto_rawDesc), len(file_offchain_gpi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_offchain_gpi_proto_goTypes,
		DependencyIndexes: file_offchain_gpi_proto_depIdxs,
		MessageInfos:      file_offchain_gpi_proto_msgTypes,
	}.Build()
	File_offchain_gpi_proto = out.File
	file_offchain_gpi_proto_goTypes = nil
	file_offchain_gpi_proto_depIdxs = nil
}
