// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: offchain/gpi.proto

// Package định nghĩa các message và service cho GPI (Global Payments Innovation) trong offchain

package offchain

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GpiService_CreatePayment_FullMethodName               = "/offchain.v1.GpiService/CreatePayment"
	GpiService_GetPayment_FullMethodName                  = "/offchain.v1.GpiService/GetPayment"
	GpiService_GetPaymentStatus_FullMethodName            = "/offchain.v1.GpiService/GetPaymentStatus"
	GpiService_ConfirmPayment_FullMethodName              = "/offchain.v1.GpiService/ConfirmPayment"
	GpiService_UnheldPayment_FullMethodName               = "/offchain.v1.GpiService/UnheldPayment"
	GpiService_ListUetr_FullMethodName                    = "/offchain.v1.GpiService/ListUetr"
	GpiService_ListTransactionHistory_FullMethodName      = "/offchain.v1.GpiService/ListTransactionHistory"
	GpiService_GetTransactionHistoryByUetr_FullMethodName = "/offchain.v1.GpiService/GetTransactionHistoryByUetr"
	GpiService_InitFundingAccount_FullMethodName          = "/offchain.v1.GpiService/InitFundingAccount"
)

// GpiServiceClient is the client API for GpiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service quản lý thanh toán GPI (Global Payments Innovation)
type GpiServiceClient interface {
	// Tạo thanh toán mới
	CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error)
	// Lấy thông tin chi tiết của một thanh toán
	GetPayment(ctx context.Context, in *GetPaymentRequest, opts ...grpc.CallOption) (*GetPaymentResponse, error)
	// Lấy trạng thái của một thanh toán
	GetPaymentStatus(ctx context.Context, in *GetPaymentStatusRequest, opts ...grpc.CallOption) (*GetPaymentResponse, error)
	// Xác nhận một thanh toán
	ConfirmPayment(ctx context.Context, in *ConfirmPaymentRequest, opts ...grpc.CallOption) (*ConfirmPaymentResponse, error)
	// Unhold một thanh toán đã được hold (chỉ sau khi expired)
	UnheldPayment(ctx context.Context, in *UnheldPaymentRequest, opts ...grpc.CallOption) (*UnheldPaymentResponse, error)
	// Lấy danh sách tất cả các giao dịch (UETR)
	ListUetr(ctx context.Context, in *ListUetrRequest, opts ...grpc.CallOption) (*ListUetrResponse, error)
	// Lấy danh sách tất cả transaction history
	ListTransactionHistory(ctx context.Context, in *ListTransactionHistoryRequest, opts ...grpc.CallOption) (*ListTransactionHistoryResponse, error)
	// Lấy transaction history theo UETR
	GetTransactionHistoryByUetr(ctx context.Context, in *GetTransactionHistoryByUetrRequest, opts ...grpc.CallOption) (*ListTransactionHistoryResponse, error)
	// Khởi tạo funding cho account (mint và deposit)
	InitFundingAccount(ctx context.Context, in *InitFundingAccountRequest, opts ...grpc.CallOption) (*InitFundingAccountResponse, error)
}

type gpiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGpiServiceClient(cc grpc.ClientConnInterface) GpiServiceClient {
	return &gpiServiceClient{cc}
}

func (c *gpiServiceClient) CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePaymentResponse)
	err := c.cc.Invoke(ctx, GpiService_CreatePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gpiServiceClient) GetPayment(ctx context.Context, in *GetPaymentRequest, opts ...grpc.CallOption) (*GetPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaymentResponse)
	err := c.cc.Invoke(ctx, GpiService_GetPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gpiServiceClient) GetPaymentStatus(ctx context.Context, in *GetPaymentStatusRequest, opts ...grpc.CallOption) (*GetPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaymentResponse)
	err := c.cc.Invoke(ctx, GpiService_GetPaymentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gpiServiceClient) ConfirmPayment(ctx context.Context, in *ConfirmPaymentRequest, opts ...grpc.CallOption) (*ConfirmPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmPaymentResponse)
	err := c.cc.Invoke(ctx, GpiService_ConfirmPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gpiServiceClient) UnheldPayment(ctx context.Context, in *UnheldPaymentRequest, opts ...grpc.CallOption) (*UnheldPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnheldPaymentResponse)
	err := c.cc.Invoke(ctx, GpiService_UnheldPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gpiServiceClient) ListUetr(ctx context.Context, in *ListUetrRequest, opts ...grpc.CallOption) (*ListUetrResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUetrResponse)
	err := c.cc.Invoke(ctx, GpiService_ListUetr_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gpiServiceClient) ListTransactionHistory(ctx context.Context, in *ListTransactionHistoryRequest, opts ...grpc.CallOption) (*ListTransactionHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTransactionHistoryResponse)
	err := c.cc.Invoke(ctx, GpiService_ListTransactionHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gpiServiceClient) GetTransactionHistoryByUetr(ctx context.Context, in *GetTransactionHistoryByUetrRequest, opts ...grpc.CallOption) (*ListTransactionHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTransactionHistoryResponse)
	err := c.cc.Invoke(ctx, GpiService_GetTransactionHistoryByUetr_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gpiServiceClient) InitFundingAccount(ctx context.Context, in *InitFundingAccountRequest, opts ...grpc.CallOption) (*InitFundingAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitFundingAccountResponse)
	err := c.cc.Invoke(ctx, GpiService_InitFundingAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GpiServiceServer is the server API for GpiService service.
// All implementations must embed UnimplementedGpiServiceServer
// for forward compatibility.
//
// Service quản lý thanh toán GPI (Global Payments Innovation)
type GpiServiceServer interface {
	// Tạo thanh toán mới
	CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentResponse, error)
	// Lấy thông tin chi tiết của một thanh toán
	GetPayment(context.Context, *GetPaymentRequest) (*GetPaymentResponse, error)
	// Lấy trạng thái của một thanh toán
	GetPaymentStatus(context.Context, *GetPaymentStatusRequest) (*GetPaymentResponse, error)
	// Xác nhận một thanh toán
	ConfirmPayment(context.Context, *ConfirmPaymentRequest) (*ConfirmPaymentResponse, error)
	// Unhold một thanh toán đã được hold (chỉ sau khi expired)
	UnheldPayment(context.Context, *UnheldPaymentRequest) (*UnheldPaymentResponse, error)
	// Lấy danh sách tất cả các giao dịch (UETR)
	ListUetr(context.Context, *ListUetrRequest) (*ListUetrResponse, error)
	// Lấy danh sách tất cả transaction history
	ListTransactionHistory(context.Context, *ListTransactionHistoryRequest) (*ListTransactionHistoryResponse, error)
	// Lấy transaction history theo UETR
	GetTransactionHistoryByUetr(context.Context, *GetTransactionHistoryByUetrRequest) (*ListTransactionHistoryResponse, error)
	// Khởi tạo funding cho account (mint và deposit)
	InitFundingAccount(context.Context, *InitFundingAccountRequest) (*InitFundingAccountResponse, error)
	mustEmbedUnimplementedGpiServiceServer()
}

// UnimplementedGpiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGpiServiceServer struct{}

func (UnimplementedGpiServiceServer) CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePayment not implemented")
}
func (UnimplementedGpiServiceServer) GetPayment(context.Context, *GetPaymentRequest) (*GetPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayment not implemented")
}
func (UnimplementedGpiServiceServer) GetPaymentStatus(context.Context, *GetPaymentStatusRequest) (*GetPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaymentStatus not implemented")
}
func (UnimplementedGpiServiceServer) ConfirmPayment(context.Context, *ConfirmPaymentRequest) (*ConfirmPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmPayment not implemented")
}
func (UnimplementedGpiServiceServer) UnheldPayment(context.Context, *UnheldPaymentRequest) (*UnheldPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnheldPayment not implemented")
}
func (UnimplementedGpiServiceServer) ListUetr(context.Context, *ListUetrRequest) (*ListUetrResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUetr not implemented")
}
func (UnimplementedGpiServiceServer) ListTransactionHistory(context.Context, *ListTransactionHistoryRequest) (*ListTransactionHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTransactionHistory not implemented")
}
func (UnimplementedGpiServiceServer) GetTransactionHistoryByUetr(context.Context, *GetTransactionHistoryByUetrRequest) (*ListTransactionHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactionHistoryByUetr not implemented")
}
func (UnimplementedGpiServiceServer) InitFundingAccount(context.Context, *InitFundingAccountRequest) (*InitFundingAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitFundingAccount not implemented")
}
func (UnimplementedGpiServiceServer) mustEmbedUnimplementedGpiServiceServer() {}
func (UnimplementedGpiServiceServer) testEmbeddedByValue()                    {}

// UnsafeGpiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GpiServiceServer will
// result in compilation errors.
type UnsafeGpiServiceServer interface {
	mustEmbedUnimplementedGpiServiceServer()
}

func RegisterGpiServiceServer(s grpc.ServiceRegistrar, srv GpiServiceServer) {
	// If the following call pancis, it indicates UnimplementedGpiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GpiService_ServiceDesc, srv)
}

func _GpiService_CreatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GpiServiceServer).CreatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GpiService_CreatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GpiServiceServer).CreatePayment(ctx, req.(*CreatePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GpiService_GetPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GpiServiceServer).GetPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GpiService_GetPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GpiServiceServer).GetPayment(ctx, req.(*GetPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GpiService_GetPaymentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GpiServiceServer).GetPaymentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GpiService_GetPaymentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GpiServiceServer).GetPaymentStatus(ctx, req.(*GetPaymentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GpiService_ConfirmPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GpiServiceServer).ConfirmPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GpiService_ConfirmPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GpiServiceServer).ConfirmPayment(ctx, req.(*ConfirmPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GpiService_UnheldPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnheldPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GpiServiceServer).UnheldPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GpiService_UnheldPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GpiServiceServer).UnheldPayment(ctx, req.(*UnheldPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GpiService_ListUetr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUetrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GpiServiceServer).ListUetr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GpiService_ListUetr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GpiServiceServer).ListUetr(ctx, req.(*ListUetrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GpiService_ListTransactionHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTransactionHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GpiServiceServer).ListTransactionHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GpiService_ListTransactionHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GpiServiceServer).ListTransactionHistory(ctx, req.(*ListTransactionHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GpiService_GetTransactionHistoryByUetr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionHistoryByUetrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GpiServiceServer).GetTransactionHistoryByUetr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GpiService_GetTransactionHistoryByUetr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GpiServiceServer).GetTransactionHistoryByUetr(ctx, req.(*GetTransactionHistoryByUetrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GpiService_InitFundingAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitFundingAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GpiServiceServer).InitFundingAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GpiService_InitFundingAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GpiServiceServer).InitFundingAccount(ctx, req.(*InitFundingAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GpiService_ServiceDesc is the grpc.ServiceDesc for GpiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GpiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "offchain.v1.GpiService",
	HandlerType: (*GpiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePayment",
			Handler:    _GpiService_CreatePayment_Handler,
		},
		{
			MethodName: "GetPayment",
			Handler:    _GpiService_GetPayment_Handler,
		},
		{
			MethodName: "GetPaymentStatus",
			Handler:    _GpiService_GetPaymentStatus_Handler,
		},
		{
			MethodName: "ConfirmPayment",
			Handler:    _GpiService_ConfirmPayment_Handler,
		},
		{
			MethodName: "UnheldPayment",
			Handler:    _GpiService_UnheldPayment_Handler,
		},
		{
			MethodName: "ListUetr",
			Handler:    _GpiService_ListUetr_Handler,
		},
		{
			MethodName: "ListTransactionHistory",
			Handler:    _GpiService_ListTransactionHistory_Handler,
		},
		{
			MethodName: "GetTransactionHistoryByUetr",
			Handler:    _GpiService_GetTransactionHistoryByUetr_Handler,
		},
		{
			MethodName: "InitFundingAccount",
			Handler:    _GpiService_InitFundingAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "offchain/gpi.proto",
}
