// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: offchain/kyc.proto

package offchain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListEntitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*KycEntity           `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntitiesResponse) Reset() {
	*x = ListEntitiesResponse{}
	mi := &file_offchain_kyc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntitiesResponse) ProtoMessage() {}

func (x *ListEntitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offchain_kyc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntitiesResponse.ProtoReflect.Descriptor instead.
func (*ListEntitiesResponse) Descriptor() ([]byte, []int) {
	return file_offchain_kyc_proto_rawDescGZIP(), []int{0}
}

func (x *ListEntitiesResponse) GetEntities() []*KycEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type GetEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bic           string                 `protobuf:"bytes,1,opt,name=bic,proto3" json:"bic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityRequest) Reset() {
	*x = GetEntityRequest{}
	mi := &file_offchain_kyc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityRequest) ProtoMessage() {}

func (x *GetEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offchain_kyc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityRequest.ProtoReflect.Descriptor instead.
func (*GetEntityRequest) Descriptor() ([]byte, []int) {
	return file_offchain_kyc_proto_rawDescGZIP(), []int{1}
}

func (x *GetEntityRequest) GetBic() string {
	if x != nil {
		return x.Bic
	}
	return ""
}

type GetEntityDocsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bic           string                 `protobuf:"bytes,1,opt,name=bic,proto3" json:"bic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityDocsRequest) Reset() {
	*x = GetEntityDocsRequest{}
	mi := &file_offchain_kyc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityDocsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityDocsRequest) ProtoMessage() {}

func (x *GetEntityDocsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offchain_kyc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityDocsRequest.ProtoReflect.Descriptor instead.
func (*GetEntityDocsRequest) Descriptor() ([]byte, []int) {
	return file_offchain_kyc_proto_rawDescGZIP(), []int{2}
}

func (x *GetEntityDocsRequest) GetBic() string {
	if x != nil {
		return x.Bic
	}
	return ""
}

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_offchain_kyc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_offchain_kyc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_offchain_kyc_proto_rawDescGZIP(), []int{3}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Document) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetEntityDocsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Document            `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityDocsResponse) Reset() {
	*x = GetEntityDocsResponse{}
	mi := &file_offchain_kyc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityDocsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityDocsResponse) ProtoMessage() {}

func (x *GetEntityDocsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offchain_kyc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityDocsResponse.ProtoReflect.Descriptor instead.
func (*GetEntityDocsResponse) Descriptor() ([]byte, []int) {
	return file_offchain_kyc_proto_rawDescGZIP(), []int{4}
}

func (x *GetEntityDocsResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

type SubmitKycRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bic           string                 `protobuf:"bytes,1,opt,name=bic,proto3" json:"bic,omitempty"`
	Updates       map[string]string      `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitKycRequest) Reset() {
	*x = SubmitKycRequest{}
	mi := &file_offchain_kyc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitKycRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitKycRequest) ProtoMessage() {}

func (x *SubmitKycRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offchain_kyc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitKycRequest.ProtoReflect.Descriptor instead.
func (*SubmitKycRequest) Descriptor() ([]byte, []int) {
	return file_offchain_kyc_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitKycRequest) GetBic() string {
	if x != nil {
		return x.Bic
	}
	return ""
}

func (x *SubmitKycRequest) GetUpdates() map[string]string {
	if x != nil {
		return x.Updates
	}
	return nil
}

type SubmitKycResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitKycResponse) Reset() {
	*x = SubmitKycResponse{}
	mi := &file_offchain_kyc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitKycResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitKycResponse) ProtoMessage() {}

func (x *SubmitKycResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offchain_kyc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitKycResponse.ProtoReflect.Descriptor instead.
func (*SubmitKycResponse) Descriptor() ([]byte, []int) {
	return file_offchain_kyc_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitKycResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type KycMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Fields        []string               `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KycMetadata) Reset() {
	*x = KycMetadata{}
	mi := &file_offchain_kyc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KycMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KycMetadata) ProtoMessage() {}

func (x *KycMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_offchain_kyc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KycMetadata.ProtoReflect.Descriptor instead.
func (*KycMetadata) Descriptor() ([]byte, []int) {
	return file_offchain_kyc_proto_rawDescGZIP(), []int{7}
}

func (x *KycMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *KycMetadata) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type AuditEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bic           string                 `protobuf:"bytes,1,opt,name=bic,proto3" json:"bic,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Time          string                 `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEntry) Reset() {
	*x = AuditEntry{}
	mi := &file_offchain_kyc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEntry) ProtoMessage() {}

func (x *AuditEntry) ProtoReflect() protoreflect.Message {
	mi := &file_offchain_kyc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEntry.ProtoReflect.Descriptor instead.
func (*AuditEntry) Descriptor() ([]byte, []int) {
	return file_offchain_kyc_proto_rawDescGZIP(), []int{8}
}

func (x *AuditEntry) GetBic() string {
	if x != nil {
		return x.Bic
	}
	return ""
}

func (x *AuditEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEntry) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type AuditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*AuditEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditResponse) Reset() {
	*x = AuditResponse{}
	mi := &file_offchain_kyc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditResponse) ProtoMessage() {}

func (x *AuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offchain_kyc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditResponse.ProtoReflect.Descriptor instead.
func (*AuditResponse) Descriptor() ([]byte, []int) {
	return file_offchain_kyc_proto_rawDescGZIP(), []int{9}
}

func (x *AuditResponse) GetEntries() []*AuditEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_offchain_kyc_proto protoreflect.FileDescriptor

const file_offchain_kyc_proto_rawDesc = "" +
	"\n" +
	"\x12offchain/kyc.proto\x12\voffchain.v1\x1a\x15offchain/common.proto\"J\n" +
	"\x14ListEntitiesResponse\x122\n" +
	"\bentities\x18\x01 \x03(\v2\x16.offchain.v1.KycEntityR\bentities\"$\n" +
	"\x10GetEntityRequest\x12\x10\n" +
	"\x03bic\x18\x01 \x01(\tR\x03bic\"(\n" +
	"\x14GetEntityDocsRequest\x12\x10\n" +
	"\x03bic\x18\x01 \x01(\tR\x03bic\"@\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"L\n" +
	"\x15GetEntityDocsResponse\x123\n" +
	"\tdocuments\x18\x01 \x03(\v2\x15.offchain.v1.DocumentR\tdocuments\"\xa6\x01\n" +
	"\x10SubmitKycRequest\x12\x10\n" +
	"\x03bic\x18\x01 \x01(\tR\x03bic\x12D\n" +
	"\aupdates\x18\x02 \x03(\v2*.offchain.v1.SubmitKycRequest.UpdatesEntryR\aupdates\x1a:\n" +
	"\fUpdatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"+\n" +
	"\x11SubmitKycResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"?\n" +
	"\vKycMetadata\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06fields\x18\x02 \x03(\tR\x06fields\"J\n" +
	"\n" +
	"AuditEntry\x12\x10\n" +
	"\x03bic\x18\x01 \x01(\tR\x03bic\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x12\n" +
	"\x04time\x18\x03 \x01(\tR\x04time\"B\n" +
	"\rAuditResponse\x121\n" +
	"\aentries\x18\x01 \x03(\v2\x17.offchain.v1.AuditEntryR\aentries2\xca\x03\n" +
	"\n" +
	"KycService\x12G\n" +
	"\fListEntities\x12\x12.offchain.v1.Empty\x1a!.offchain.v1.ListEntitiesResponse\"\x00\x12D\n" +
	"\tGetEntity\x12\x1d.offchain.v1.GetEntityRequest\x1a\x16.offchain.v1.KycEntity\"\x00\x12]\n" +
	"\x12GetEntityDocuments\x12!.offchain.v1.GetEntityDocsRequest\x1a\".offchain.v1.GetEntityDocsResponse\"\x00\x12L\n" +
	"\tSubmitKyc\x12\x1d.offchain.v1.SubmitKycRequest\x1a\x1e.offchain.v1.SubmitKycResponse\"\x00\x12:\n" +
	"\bMetadata\x12\x12.offchain.v1.Empty\x1a\x18.offchain.v1.KycMetadata\"\x00\x12D\n" +
	"\x05Audit\x12\x1d.offchain.v1.GetEntityRequest\x1a\x1a.offchain.v1.AuditResponse\"\x00BU\n" +
	"\x1ccom.blcvn.switching.offchainZ5github.com/blcvn/switching-proto/go/offchain;offchainb\x06proto3"

var (
	file_offchain_kyc_proto_rawDescOnce sync.Once
	file_offchain_kyc_proto_rawDescData []byte
)

func file_offchain_kyc_proto_rawDescGZIP() []byte {
	file_offchain_kyc_proto_rawDescOnce.Do(func() {
		file_offchain_kyc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_offchain_kyc_proto_rawDesc), len(file_offchain_kyc_proto_rawDesc)))
	})
	return file_offchain_kyc_proto_rawDescData
}

var file_offchain_kyc_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_offchain_kyc_proto_goTypes = []any{
	(*ListEntitiesResponse)(nil),  // 0: offchain.v1.ListEntitiesResponse
	(*GetEntityRequest)(nil),      // 1: offchain.v1.GetEntityRequest
	(*GetEntityDocsRequest)(nil),  // 2: offchain.v1.GetEntityDocsRequest
	(*Document)(nil),              // 3: offchain.v1.Document
	(*GetEntityDocsResponse)(nil), // 4: offchain.v1.GetEntityDocsResponse
	(*SubmitKycRequest)(nil),      // 5: offchain.v1.SubmitKycRequest
	(*SubmitKycResponse)(nil),     // 6: offchain.v1.SubmitKycResponse
	(*KycMetadata)(nil),           // 7: offchain.v1.KycMetadata
	(*AuditEntry)(nil),            // 8: offchain.v1.AuditEntry
	(*AuditResponse)(nil),         // 9: offchain.v1.AuditResponse
	nil,                           // 10: offchain.v1.SubmitKycRequest.UpdatesEntry
	(*KycEntity)(nil),             // 11: offchain.v1.KycEntity
	(*Empty)(nil),                 // 12: offchain.v1.Empty
}
var file_offchain_kyc_proto_depIdxs = []int32{
	11, // 0: offchain.v1.ListEntitiesResponse.entities:type_name -> offchain.v1.KycEntity
	3,  // 1: offchain.v1.GetEntityDocsResponse.documents:type_name -> offchain.v1.Document
	10, // 2: offchain.v1.SubmitKycRequest.updates:type_name -> offchain.v1.SubmitKycRequest.UpdatesEntry
	8,  // 3: offchain.v1.AuditResponse.entries:type_name -> offchain.v1.AuditEntry
	12, // 4: offchain.v1.KycService.ListEntities:input_type -> offchain.v1.Empty
	1,  // 5: offchain.v1.KycService.GetEntity:input_type -> offchain.v1.GetEntityRequest
	2,  // 6: offchain.v1.KycService.GetEntityDocuments:input_type -> offchain.v1.GetEntityDocsRequest
	5,  // 7: offchain.v1.KycService.SubmitKyc:input_type -> offchain.v1.SubmitKycRequest
	12, // 8: offchain.v1.KycService.Metadata:input_type -> offchain.v1.Empty
	1,  // 9: offchain.v1.KycService.Audit:input_type -> offchain.v1.GetEntityRequest
	0,  // 10: offchain.v1.KycService.ListEntities:output_type -> offchain.v1.ListEntitiesResponse
	11, // 11: offchain.v1.KycService.GetEntity:output_type -> offchain.v1.KycEntity
	4,  // 12: offchain.v1.KycService.GetEntityDocuments:output_type -> offchain.v1.GetEntityDocsResponse
	6,  // 13: offchain.v1.KycService.SubmitKyc:output_type -> offchain.v1.SubmitKycResponse
	7,  // 14: offchain.v1.KycService.Metadata:output_type -> offchain.v1.KycMetadata
	9,  // 15: offchain.v1.KycService.Audit:output_type -> offchain.v1.AuditResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_offchain_kyc_proto_init() }
func file_offchain_kyc_proto_init() {
	if File_offchain_kyc_proto != nil {
		return
	}
	file_offchain_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_offchain_kyc_proto_rawDesc), len(file_offchain_kyc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_offchain_kyc_proto_goTypes,
		DependencyIndexes: file_offchain_kyc_proto_depIdxs,
		MessageInfos:      file_offchain_kyc_proto_msgTypes,
	}.Build()
	File_offchain_kyc_proto = out.File
	file_offchain_kyc_proto_goTypes = nil
	file_offchain_kyc_proto_depIdxs = nil
}
